---
sidebar: sidebar
permalink: about-file-systems-fsx.html
keywords: overview, FSx file system, ONTAP file system, Workload Factory, storage
summary: 
---
= About FSx for ONTAP file systems
:icons: font
:imagesdir: ./media/

[.lead]
FSx for ONTAP file systems provide simple, agile, secure, and scalable storage. 

== File systems
An FSx for ONTAP file system supports workload capabilities in Workload Factory. 

== File system storage VMs
In FSx for ONTAP, volumes are hosted on virtual file servers called storage virtual machines (SVMs). An SVM is an isolated file server with its own administrative credentials and endpoints for administering and accessing data. When you access data in FSx for ONTAP, your clients and workstations mount a volume, SMB share, or iSCSI LUN hosted by an SVM using the SVM's endpoint (IP address).

When you create an FSx for ONTAP file system, Amazon FSx/NetApp(?) automatically creates a default SVM on your file system. You can create additional SVMs on your file system at any time using the user interface, (other tools? what can't you use?).

== File system backup

== File system replication


== File system storage inventory
The *Storage inventory* screen provides a overview of an FSx for ONTAP file system. From the *Storage inventory* screen, you can view the following: 

* Overview
* Volumes
* Storage VMs
* Replication relationships
* Information

=== Overview
The Overview shows an FSx for ONTAP file system name, its status, HA configuration, and number of HA pairs. Additionally, it shows the number of volumes, storage VMs, and replication relationships in the file system and gives you the option to create any of these storage features.

You can also view charts and graphs on utilization, latency, protected volumes, capacity utilization...(Can't see this from the Figma - need to verify in demo or stage)

From the Overview screen, you can use the breadcrumb trail to navigate back to the storage screen. 

An Associate link may appear in the header as well as the option to refresh the screen and a menu for more options. 

=== Information
The following details are shown under *Information*:

* General details
* Capacity distribution
* Performance
* Environment
* Encryption
* AWS Backup

(Need to verify what each information button + shows)

You can use the breadcrumb trail to navigate back to the storage screen. 

An Associate link may appear in the header as well as the option to refresh the screen and a menu for more options. 
