---
sidebar: sidebar
permalink: add-ha-pairs.html
keywords: add high-availability pairs, add HA pairs, add HA pair, add high-availability pair, scale out, file system, fsx for ontap
summary: "Add high-availability pairs to a file system in BlueXP workload factory to scale out the file system." 
---
= Add HA pairs to a file system in BlueXP workload factory
:icons: font
:imagesdir: ./media/

[.lead]
Add HA pairs to scale out an FSx for ONTAP second-generation Single-AZ file system in BlueXP workload factory to increase performance and capacity. This expansion gives you more performance scalability and flexibility over first-generation file systems. 

.About this task 
This operation is irreversible. 

The new HA pairs get added using the same SKU and same capacity per HA pair.

Consider the following before adding HA pairs to a file system: 

* *HA pair removal*: HA pairs cannot be removed once added to the file system. 
* *Operation time and limitations*: Adding HA pairs may take approximately 30 minutes. Consider adding HA pairs during a maintenance window or during low activity periods. 
* *Solo operation*: Adding HA pairs is a solo operation and can't be done in parallel with other operations. 
* *IO allocation*: Automatic IO allocation depends on total storage capacity. User-configured IO allocation is multiplied by the amount of HA pairs added.
* *NVMe cache*: When adding HA pairs, NVME cache is enabled by default. We recommend turning off NVMe cache for heavy workloads.
* *Number of HA pairs*: We recommend expanding your file system to an even number of HA pairs for balanced data distribution across HA pairs.
* *LUN creation*: LUN creation is possible on a second-generation Single-AZ file system only if LUNs don't already exist on the file system when adding HA pairs. LUN creation is only supported on a file system with 6 HA pairs or fewer. 
* *Unsupported configurations*: Adding HA pairs isn't supported for the following: 
** Multi-AZ HA deployments or first-generation FSx for ONTAP file systems
** FSx for ONTAP file systems with more than 5 storage VMs
** FSx for ONTAP file systems with iSCSI LUNs
** Configurations which have maximum or close to maximum SSD capacity or have reached IO allocation limits

.Before you begin
Do the following before you add HA pairs to a file system:

* Remove all iSCSI LUNs to scale out the file system.
* Make sure that the file system has no more than 5 storage VMs.

.Steps
. Log in using one of the link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html[console experiences^].
. In Storage, select *Go to storage inventory*.
. In the *FSx for ONTAP* tab, under *Information*, select the pencil icon next to *HA pairs*.
. In the *Add HA pairs* dialog, select the number of HA pairs to add to the file system.
. Select *Add* to confirm the addition of the HA pairs.

.Result
Workload factory initiates the process to add the HA pair(s) to the file system. The file system isn't available for other operations like volume creation until the HA pairs are added. You can monitor the progress of the operation in the *Tracker* tab.

