---
sidebar: sidebar
permalink: cascade-replication.html
keywords: replicate, cascade, cascade replication, cascade deployment, data protection, volume replication, replicate data protection volume
summary: "Replicate data protection volumes, or cascade the replication of volume data, to extend data protection to tertiary systems or migrate your data." 
---
= Replicate data protection volumes in BlueXP workload factory
:icons: font
:imagesdir: ./media/

[.lead]
Replicate data protection volumes, or cascade the replication of volume data, to extend data protection to tertiary systems or migrate your data. 

.About this task
BlueXP workload factory supports replicating data protection volumes, also called _cascade deployments_. A _cascade deployment_ consists of a chain of relationships in which a source volume is mirrored to a secondary volume (first hop), and the secondary volume is mirrored to a tertiary volume (second hop). If the secondary volume becomes unavailable, you can synchronize the relationship between the primary and tertiary volumes without performing a new baseline transfer.

This feature is supported for FSx for ONTAP file systems with ONTAP version 9.6 and higher. Refer to link:https://docs.netapp.com/us-en/ontap/data-protection/compatible-ontap-versions-snapmirror-concept.html#snapmirror-disaster-recovery-relationships[ONTAP documentation for compatible ONTAP versions^].

Learn more about link:https://docs.netapp.com/us-en/ontap/data-protection/supported-deployment-config-concept.html#how-cascade-deployments-work[how cascade deployments work^].

.Before you begin
Consider the following before you begin: 

* Be aware that volumes that are part of a cascade configuration can take longer to resynchronize.
* If the source volume of the relationship is a data protection volume and is a target of another relationship, reversing the replication relationship isn't supported.
* Workload factory doesn't support a third hop. 

[role="tabbed-block"]
====

.Replicate a single volume
--
You can replicate a data protection (DP) volume. 

NOTE: One replica of a data protection volume is supported. You cannot create a second replica of a DP volume.

.Steps
. Log in using one of the link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html[console experiences^].
. In Storage, select Go to storage inventory.
. In the FSx for ONTAP tab, select the three-dot menu of the file system to update and then select Manage.
. Select the Volumes tab.  
. Select the three-dot menu of the data protection volume (DP/replicated volume) and select *Replicate volume data*. 
. On the Create replication page, under Replication target, provide the following: 
.. *FSx for ONTAP file system*: Select credentials, region, and FSx for ONTAP file system name for the target FSx for ONTAP file system.
.. *Storage VM name*: Select the storage VM from the dropdown menu.
.. *Volume name*: The target volume name is generated automatically with the following format `{OriginalVolumeName}_copy`. You can use the auto-generated volume name or enter another volume name. 
.. *Use case*: Select one of the following use cases for the replication.
* Migration: transfers your data to the target FSx for ONTAP file system
* Hot disaster recovery: ensures high availability and rapid disaster recovery for critical workloads
* Cold or archive disaster recovery: 
** Cold disaster recovery: uses longer recovery time objectives (RTO) and recovery point objects (RPO) to lower costs
** Archive: replicates data for long-term storage and compliance
* Other
.. *Tiering policy*: Select the tiering policy for the data stored in the target volume. Depending on the use case you selected, the tiering policy defaults to the recommended tiering policy for the use case. 
+
_Balanced (Auto)_ is the default tiering policy when creating a volume using the workload factory FSx for ONTAP user interface. For more information about volume tiering policies, refer to link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/volume-storage-capacity.html#data-tiering-policy[Volume storage capacity^] in AWS FSx for NetApp ONTAP documentation. 
.. *Max transfer rate*: Select *Limited* and enter the max transfer limit in MB/s. Alternatively, select *Unlimited*. 
+
Without a limit, network and application performance may decline. Alternatively, we recommend an unlimited transfer rate for FSx for ONTAP file systems for critical workloads, for example, those that are used primarily for disaster recovery. 
. Under Replication settings, provide the following: 
.. *Replication interval*: Select the frequency that snapshots are transferred from the source volume to the target volume. 
.. *Long-term retention*: Optionally, enable snapshots for long-term retention. 
+
If you enable long-term retention, then select an existing policy or create a new policy to define the snapshots to replicate and the number to retain.  
+
* For *Choose an existing policy*, select an existing policy from the dropdown menu. 
* For *Create a new policy*, provide the following: 
** *Policy name*: Enter a policy name. 
** *Snapshot policies*: In the table, select the snapshot policy frequency and the number of copies to retain. You can select more than one snapshot policy. 
. Select *Create*. 
--
.Replicate all volumes in a file system
--
You can replicate all data protection (DP) volumes in a file system. 

NOTE: One replica of a data protection volume is supported. You cannot create a second replica of a DP volume.

.Steps
. Log in using one of the link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html[console experiences^].
. In Storage, select *Go to storage inventory*. 
. In the FSx for ONTAP tab, select the three-dot menu of the file system with the volumes and then select *Manage*.  
. From the file system overview, select *Create replication*. 
. On the Create replication page, under Replication target, provide the following: 
.. *FSx for ONTAP file system*: Select credentials, region, and FSx for ONTAP file system name for the target FSx for ONTAP file system.
.. *Storage VM name*: Select the storage VM from the dropdown menu.
.. *Volume name*: The target volume name is generated automatically with the following format `{OriginalVolumeName}_copy`.
.. *Tiering policy*: Select the tiering policy for the data stored in the target volume. 
+
_Auto_ is the default tiering policy when creating a volume using the workload factory FSx for ONTAP user interface. For more information about volume tiering policies, refer to link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/volume-storage-capacity.html#data-tiering-policy[Volume storage capacity^]in AWS FSx for NetApp ONTAP documentation. 
.. *Max transfer rate*: Select *Limited* and enter the max transfer limit in MiB/s. Alternatively, select *Unlimited*. 
+
Without a limit, network and application performance may decline. Alternatively, we recommend an unlimited transfer rate for FSx for ONTAP file systems for critical workloads, for example, those that are used primarily for disaster recovery. 
. Under Replication settings, provide the following: 
.. *Replication interval*: Select the frequency that snapshots are transferred from the source volume to the target volume. 
.. *Long-term retention*: Optionally, enable snapshots for long-term retention. 
+
If you enable long-term retention, then select an existing policy or create a new policy to define the snapshots to replicate and the number to retain.  
+
* For *Choose an existing policy*, select an existing policy from the dropdown menu. 
* For *Create a new policy*, provide the following: 
** *Policy name*: Enter a policy name. 
** *Snapshot policies*: In the table, select the snapshot policy frequency and the number of copies to retain. You can select more than one snapshot policy. 
. Select *Create*. 
--

====

.Result
The replicated volume or volumes replicate and appear in the *Replication relationships* tab in the target FSx for ONTAP file system.  
