---
sidebar: sidebar
permalink: cascade-replication.html
keywords: replicate, cascade, cascade replication, cascade deployment, data protection, volume replication, replicate data protection volume
summary: "Replicate data protection volumes, or cascade the replication of volume data, to extend data protection to tertiary systems or migrate your data." 
---
= Replicate data protection volumes in NetApp Workload Factory
:icons: font
:imagesdir: ./media/

[.lead]
Replicate data protection volumes, or cascade the replication of volume data, to extend data protection to tertiary systems or migrate your data. 

.About this task
NetApp Workload Factory supports replicating data protection volumes, also called _cascade deployments_. A _cascade deployment_ consists of a chain of relationships in which a source volume is mirrored to a secondary volume (first hop), and the secondary volume is mirrored to a tertiary volume (second hop). If the secondary volume becomes unavailable, you can synchronize the relationship between the primary and tertiary volumes without performing a new baseline transfer.

This feature is supported for FSx for ONTAP file systems with ONTAP version 9.6 and higher. Refer to link:https://docs.netapp.com/us-en/ontap/data-protection/compatible-ontap-versions-snapmirror-concept.html#snapmirror-disaster-recovery-relationships[ONTAP documentation for compatible ONTAP versions^].

Learn more about link:https://docs.netapp.com/us-en/ontap/data-protection/supported-deployment-config-concept.html#how-cascade-deployments-work[how cascade deployments work^].

.Before you begin
Consider the following before you begin: 

* Be aware that volumes that are part of a cascade configuration can take longer to resynchronize.
* If the source volume of the relationship is a data protection volume and is a target of another relationship, reversing the replication relationship isn't supported.
* One replica of a data protection volume (or a second hop) is supported. It isn't considered best practice to create a second replica of a data protection volume (or a third hop). 

.Steps
. Log in using one of the link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html[console experiences^].
. In the Storage tile, select *Go to Storage*. 
. From the Storage menu, select *FSx for ONTAP*. 
. From *FSx for ONTAP*, select the actions menu of the file system that contains the volume(s) to replicate and then select *Manage*.
. From the file system overview, select the *Volumes* tab.
. In the Volumes table, select one or more data protection volumes (DP/replicated volumes), and then select *Replicate data*. 
. On the Replicate data page, under Replication target, provide the following: 
.. *FSx for ONTAP file system*: Select credentials, region, and FSx for ONTAP file system name for the target FSx for ONTAP file system.
.. *Storage VM name*: Select the storage VM from the dropdown menu.
.. *Volume name*: The target volume name is generated automatically with the following format `{OriginalVolumeName}_copy`. You can use the auto-generated volume name or enter another volume name. 
.. *Use case*: Select one of the following use cases for the replication. Depending on the selected use case, Workload Factory fills in the form with recommended values in accordance with best practices. You can accept the recommended values or make changes as you complete the form.  
* Migration: transfers your data to the target FSx for ONTAP file system
* Hot disaster recovery: ensures high availability and rapid disaster recovery for critical workloads
* Cold or archive disaster recovery: 
** Cold disaster recovery: uses longer recovery time objectives (RTO) and recovery point objects (RPO) to lower costs
** Archive: replicates data for long-term storage and compliance
* Other
.. *Tiering policy*: Select the tiering policy for the data stored in the target volume. The tiering policy defaults to the recommended tiering policy for the use case you selected.
+
_Balanced (Auto)_ is the default tiering policy when creating a volume using the Workload Factory console. For more information about volume tiering policies, refer to link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/volume-storage-capacity.html#data-tiering-policy[Volume storage capacity^] in AWS FSx for NetApp ONTAP documentation. Note that Workload factory uses use-case based names in the Workload Factory console for tiering policies and includes FSx for ONTAP tiering policy names in parentheses.
+
If you selected the migration use case, Workload Factory automatically selects to copy the tiering policy of source volume to the target volume. You can deselect to copy the tiering policy and select a tiering policy which applies to the volume selected for replication. 

.. *Max transfer rate*: Select *Limited* and enter the max transfer limit in MB/s. Alternatively, select *Unlimited*. 
+
Without a limit, network and application performance may decline. Alternatively, we recommend an unlimited transfer rate for FSx for ONTAP file systems for critical workloads, for example, those that are used primarily for disaster recovery. 
. Under Replication settings, provide the following: 
.. *Replication interval*: Select the frequency that snapshots are transferred from the source volume to the target volume. 
.. *Long-term retention*: Optionally, enable snapshots for long-term retention. Long-term retention enables business services to continue operating even through a complete site failure, supporting applications to fail over transparently using a secondary copy.
+
Replications without long-term retention use the _MirrorAllSnapshots_ policy. Enabling long-term retention assigns the _MirrorAndVault_ policy to the replication.
+
If you enable long-term retention, then select an existing policy or create a new policy to define the snapshots to replicate and the number to retain. 
+
NOTE: Matching source and target labels are required for long-term retention. If desired, Workload factory can create missing labels for you. 
+
* *Choose an existing policy*: select an existing policy from the dropdown menu. 
* *Create a new policy*: provide the following: 
** *Policy name*: Enter a policy name.
** Optional: Enable immutable snapshots.
*** Select *Enable immutable snapshots* to prevent snapshots taken in this policy from being deleted during the retention period.
*** Set the *Retention period* in number of hours, days, months, or years. 
** *Snapshot policies*: In the table, select the snapshot policy frequency and the number of copies to retain. You can select more than one snapshot policy. 
. Select *Create*. 

.Result
The replicated volume or volumes replicate and appear in the *Replication relationships* tab in the target FSx for ONTAP file system.  
