---
sidebar: sidebar
permalink: cascade-replication.html
keywords: replicate, cascade, cascade replication, cascade deployment, data protection, volume replication, replicate data protection volume
summary: "Replicate data protection volumes, or cascade the replication of volume data, to extend data protection to tertiary systems." 
---
= Use cascading replication in BlueXP workload factory
:icons: font
:imagesdir: ./media/

[.lead]
Replicate data protection volumes, or cascade the replication of volume data, to extend data protection to tertiary systems. 

.About this task
BlueXP workload factory supports replicating data protection volumes. In ONTAP, replicating data protection volumes is considered a _mirror-mirror cascade deployment_. A mirror-mirror cascade deployment consists of a chain of relationships in which a source volume is mirrored to a secondary volume, and the secondary volume is mirrored to a tertiary volume. If the secondary volume becomes unavailable, you can synchronize the relationship between the primary and tertiary volumes without performing a new baseline transfer.

This feature is supported for FSx for ONTAP file systems with ONTAP version 9.6 and higher. Refer to link:https://docs.netapp.com/us-en/ontap/data-protection/compatible-ontap-versions-snapmirror-concept.html#snapmirror-disaster-recovery-relationships[ONTAP documentation for compatible ONTAP versions^].

NOTE: If the source volume of the relationship is a data protection volume and is a target of another relationship, reversing the replication relationship isn't supported.

.Before you begin
Be aware that volumes that are part of a cascade configuration can take longer to resynchronize.

.Steps
. Log in using one of the link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html[console experiences^].
. In Storage, select Go to storage inventory.
. In the FSx for ONTAP tab, select the three-dot menu of the file system to update and then select Manage.
. Select the Volumes tab.  
. Select the three-dot menu of the data protection volume (DP/replicated volume) and select *Replicate volume data*. 

.Result
The data protection volume is replicated.