---
sidebar: sidebar
permalink: change-replication-schedule.html
keywords: change replication schedule, update replication schedule, edit replication schedule
summary: "Change the replication schedule of the source volume in a replication relationship in NetApp Workload Factory." 
---
= Change the replication schedule of a source volume
:icons: font
:imagesdir: ./media/

[.lead]
Change the replication schedule of the source volume in a replication relationship in NetApp Workload Factory. 

Choose how frequently snapshots from the source volume are transferred to the replicated volume to match your required point objectives (RPOs). 

When an on-premises ONTAP cluster is the target for the replication relationship, changing the replication schedule isn't supported. 

.Steps
. Log in using one of the link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html[console experiences^].
. In the Storage tile, select *Go to Storage*. 
. From the Storage menu, select *FSx for ONTAP*. 
. From *FSx for ONTAP*, select the actions menu of the file system to update and then select *Manage*.  
. From the file system overview, select the *Replication relationships* tab. 
. In the Replication relationships tab, select the actionsenu of the replication relationship schedule to change. 
. Select *Edit replication interval*. 
. In the Edit replication interval dialog, select the frequency of snapshot transfer from the source volume. You may select between the following frequencies: 
+
* Every 5 minutes
* Hourly
* Every 8 hours
* Daily
* Weekly
. Select *Apply*. 
