---
sidebar: sidebar
permalink: change-snapshot-policy.html
keywords: snapshot policy, snapshot schedule, modify snapshot policy, edit snapshot policy, change snapshot policy
summary: "Update the snapshot policy of a volume in BlueXP workload factory at any time." 
---
= Change the snapshot policy of a volume in BlueXP workload factory
:icons: font
:imagesdir: ./media/

[.lead]
Update the frequency of snapshots taken for a volume or disable automatic snapshots at any time. 

.Before you begin
To display existing snapshot policies, you need to associate a link. To associate a link, select *Associate link* under *Account name*. Then return to this operation. 

.Steps
. Log in using one of the link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html[console experiences^].
. In Storage, select *Go to storage inventory*.  
. In the *FSx for ONTAP* tab, select the three-dot menu of the FSx for ONTAP file system which contains the volume with the snapshot policy to update and then select *Manage*. 
. From the Overview tab of the file system, select the *Volumes* tab. 
. Select the *Volumes* tab. 
. In the *Volumes* tab, select the three-dot menu of the volume to change the snapshot policy for.
. Select *Data protection actions*, *Snapshots*, then *Manage snapshot policies*. 
. On the Snapshot policy management page, select *Change an existing snapshot policy*.
. In the *Snapshot policy name* field, select a different snapshot policy for this volume.
+ 
To disable automatic snapshots, select `none`.
+ 
If no other snapshot policies exist, link:create-snapshot-policy.html[create a new snapshot policy for this volume]. 
. Select *Apply* to save the changes. 
