---
sidebar: sidebar
permalink: change-tiering-policy.html
keywords: tiering policy, change tier, change tiers, tier policy update
summary: "Change the tiering policy in BlueXP workload factory to re-allocate data from the high-performance primary storage tier to the secondary capacity pool storage tier."
---
= Change the tiering policy of a volume in BlueXP workload factory
:icons: font
:imagesdir: ./media/

[.lead]
In BlueXP workload factory, you can change the tiering policy to automatically re-allocate data from the high-performance primary storage tier to the secondary capacity pool storage tier. 

.About this task
You can change the tiering policy of a volume at any time. The tiering policy is defined per volume. 

Deciding where your data is stored has implications for your cost savings. 

FSx for ONTAP has two tiers for storing volume data:

* *SSD storage tier*: This primary storage tier is for the data you access most frequently, also known as _hot_ data. Storing data in the primary storage tier is more expensive than in the secondary storage tier. 
* *Capacity pool storage tier*: This secondary storage tier is for archived data or infrequently accessed data, also known as _cold_ data. 

Refer to link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/managing-storage-capacity.html#storage-tiers[Managing storage capacity^] in AWS for FSx for NetApp ONTAP documentation for more information about storage tiers.

.Before you begin
Review the available tiering policies before you change the tiering policy.

* *Migration*: Recommended for migration use cases. Applies the same tiering policy from the source volume to destination volume(s).
* *Balanced (Auto)*: default tiering policy when creating a volume using the user interface. Keeps frequently accessed data in the SSD storage tier and tiers infrequently accessed data and snapshots to the capacity pool storage tier after the cooling period ends. Recommended for general primary workloads. 
* *Cost-optimized (All)*: Tiers all snapshots and data to the capacity pool storage tier. Recommended for secondary targets.
* *Performance optimized (Snapshots only)*: Tiers only snapshot data to the capacity pool storage tier. Recommended for low-latency workloads such as mission-critical databases.
* *None*: Keeps volume data in the SSD storage tier, preventing it from being moved to the capacity pool storage tier.

Note that some tiering policies have an associated minimum cooling period which sets the time, or _cooling days_, that user data in a volume must remain inactive for the data to be considered "cold" and moved to the capacity pool storage tier. The cooling period starts when data is written to the disk. 

.Steps
. Log in using one of the link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html[console experiences^].
. In Storage, select *Go to storage inventory*.
. In the *FSx for ONTAP* tab, select the three-dot menu of the file system with the volume to update and then select *Manage*.
. From the file system overview, select the *Volumes* tab. 
. From the Volumes tab, select the three-dot menu of the volume to change the tiering policy for. 
. Select *Advanced actions*, then *Change tiering policy*.  
. On the Change tiering policy page, select one of the following tiering policies: 
+
* *Auto*: Enter the number of cooling days. 
* *Snapshot only*: Enter the number of cooling days. 
* *None*
* *All*
. Select *Apply*.
