---
sidebar: sidebar
permalink: change-replication-schedule.html
keywords: change replication schedule, update replication schedule, edit replication schedule
summary: Change the replication schedule of the source volume in a replication relationship. 
---
= Change the replication schedule of a source volume
:icons: font
:imagesdir: ./media/

[.lead]
Change the replication schedule of the source volume in a replication relationship. 

Choose how frequently snapshots from the source volume are transferred to the replicated volume to match your required point objectives (RPOs). 

.Steps
. Log in to the Workload Factory console. 
. In Storage, select *Go to storage inventory*. 
. In Storage, select the *Replication relationships* tab. 
. Click the three dots menu of the replication relationship schedule to change. 
. Select *Edit replication interval*. 
. In the Edit replication interval dialog, select the frequency of snapshot transfer from the source volume. You may select between the following frequencies: 
.. Every 5 minutes
.. Hourly
.. Every 8 hours
.. Daily
.. Weekly
. Click *Apply*. 
