---
sidebar: sidebar
permalink: clone-volume.html
keywords: clone volume, clone, clone data 
summary: "Clone a volume in NetApp Workload Factory to make a read/write volume of the original volume for testing." 
---
= Clone a volume in NetApp Workload Factory
:icons: font
:imagesdir: ./media/

[.lead]
Clone a volume in NetApp Workload Factory to make a read/write volume of the original volume for testing. 

The clone reflects the current, point-in-time state of the data. You can also use clones to give additional users access to data without giving them access to production data.

.About this task
Volume cloning is only supported for FlexClone volumes. 

When a volume is cloned, a writeable volume is created with references to snapshots from the parent volume. Clone creation occurs in seconds. The cloned data doesn't reside on the volume clone but instead resides on the parent volume. Any new data written to the volume after clone creation resides on the clone.

For a cloned volume to contain all data from the parent volume and any new data added to the clone after creation, you'll need to link:split-cloned-volume.html[split the clone] from the parent volume. Additionally, you can't delete a parent volume if it has a clone. A clone must be split before a parent volume can be deleted. 

.Steps
. Log in using one of the link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html[console experiences^].
. In the Storage tile, select *Manage*.
. From the Storage menu, select *FSx for ONTAP*. 
. From *FSx for ONTAP*, select the actions menu of the FSx for ONTAP file system which contains the volume to clone then select *Manage*. 
. From the Overview tab of the file system, select the *Volumes* tab.  
. In the Volumes tab, select the actions menu of the volume to clone. 
. Select *Data protection actions*, then *Clone volume*. 
. In the Clone volume dialog, enter a name for the volume clone. 
. Select *Clone*. 
