---
sidebar: sidebar
permalink: clone-volume.html
keywords: clone volume
summary: Clone a volume to make a read-write volume of the original volume for testing. 
---
= Clone a volume
:icons: font
:imagesdir: ./media/

[.lead]
Clone a volume to make a read-write volume of the original volume for testing. 

The clone reflects the current, point-in-time state of the data. You can also use clones to give additional users access to data without giving them access to production data.

== About this task
Volume cloning is only supported for FlexClone volumes. 

When a volume is cloned, a writeable volume is created with references to snapshots from the parent volume. Clone creation occurs in seconds. The cloned data doesn't reside on the volume clone but instead resides on the parent volume. Any new data written to the volume after clone creation resides on the clone.

For a cloned volume to contain all data from the parent volume and any new data added to the clone after creation, you'll need to link:split-cloned-volume.html[split the clone^] from the parent volume. Additionally, you can't delete a parent volume if it has a clone. A clone must be split before a parent volume can be deleted. 

.Steps
. Log in to the Workload Factory console. 
. In Storage, select *Go to storage inventory*. 
. Select the *Volumes* tab. 
. In the Volumes tab, select the three dots menu of the volume to clone. 
. Select *Data protection actions*, then *Clone volume*. 
. In the Clone volume dialog, enter a name for the volume clone. 
. Click *Clone*. 
