---
sidebar: sidebar
permalink: configuration-analysis.html
keywords: configuration issues, issues, improve, analyze, storage configuration, Amazon FSx for NetApp ONTAP, FSx for ONTAP, recommendation, recommendations
summary: "NetApp Workload Factory analyzes Amazon FSx for NetApp ONTAP file system configurations regularly to determine if any there are any configuration issues."  
---
= Configuration analysis for FSx for ONTAP file systems
:icons: font
:imagesdir: ./media/

[.lead]
NetApp Workload Factory analyzes Amazon FSx for NetApp ONTAP file system configurations regularly to determine if any there are any configuration issues. When issues are found, Workload Factory shows you what the issues are and explains what needs to change to ensure your file system storage achieves peak performance, cost efficiency, and compliance with best practices. 

Key capabilities include: 

* Daily configuration analysis
* Automatic best practice validations
* Proactive observability
* Insights to action
* AWS Well-Architected Framework advisor

include::https://raw.githubusercontent.com/NetAppDocs/workload-setup-admin/main/_include/well-architected-workloads.adoc[]

== Analysis requirements
For a complete file system analysis, you must do the following: 

* Associate a link. Link connectivity lets Workload Factory analyze all file system configurations like data protection and performance.
+
link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html[Learn how to associate an existing link or to create and associate a new link]. 
* Grant _view, planning, and analysis_ permissions in your AWS account. 
+
link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html[Learn how to grant permissions to an AWS account^]

include::https://raw.githubusercontent.com/NetAppDocs/console-well-architected/main/_include/fsx-configurations.adoc[]

.What's next

link:improve-configurations.html[Implement well-architected file system configurations]

