---
sidebar: sidebar
permalink: create-replication.html
keywords: replication, replicate
summary: "Create a replication relationship for an FSx for ONTAP file system to avoid data loss in case of an unforeseen disaster."
---
= Create a replication relationship in BlueXP workload factory
:icons: font
:imagesdir: ./media/

[.lead]
Create a replication relationship for an FSx for ONTAP file system in BlueXP workload factory to avoid data loss in case of an unforeseen disaster.

.About this task
Replication is an added layer of data protection which is essential in case the region where your data resides experiences a disaster. Data loss can be avoided if you use cross-region replication. 

This operation creates a replication relationship for one or all source volumes in an FSx for ONTAP file system. 

Replicated volumes in the target file system are data protection (DP) volumes and follow the naming format: `{OriginalVolumeName}_copy`.

When replicating a source volume with immutable files, the target volume and file system  become locked until the retention period of the immutable files in the source volume ends. The immutable files feature is available when you link:create-volume.html[create a volume] for an FSx for ONTAP file system. 

.Before you begin
Make sure you meet the following prerequisites before you begin. 

* You must have two available file systems in your storage inventory to create a replication relationship.
* The two file systems you use for the replication relationship must have an associated link. link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html[Learn how to associate an existing link or to create and associate a new link]. After the link associates, return to this operation. 

Complete the following steps to replicate select volumes or replicate all volumes in a file system. 

You can replicate one source (read/write) volume or one data protection (DP) volume. Cascading replication is supported, but a third hop isn't. Learn more about link:https://review.docs.netapp.com/us-en/workload-fsx-ontap_cascade-replication/cascade-replication.html[cascading replication^]. 

.Steps
. Log in using one of the link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html[console experiences^].
. In Storage, select *Go to storage inventory*. 
. In the *FSx for ONTAP* tab, select the three-dot menu of the file system that contains the volume(s) to replicate and then select *Manage*.
. Either replicate all volumes in a file system or replicate select volumes. 
* To replicate all volumes in a file system: From the file system overview, select *Replicate data*.
* To replicate select volumes: From the file system overview, select the *Volumes* tab.
+
In the Volumes table, select one or more volumes and then select *Replicate data*. 
. On the Replicate data page, under Replication target, provide the following: 
.. *FSx for ONTAP file system*: Select credentials, region, and FSx for ONTAP file system name for the target FSx for ONTAP file system.
.. *Storage VM name*: Select the storage VM from the dropdown menu.
.. *Volume name*: The target volume name is generated automatically with the following format `{OriginalVolumeName}_copy`. You can use the auto-generated volume name or enter another volume name. 
.. *Use case*: Select one of the following use cases for the replication. Depending on the selected use case, workload factory fills in the form with recommended values in accordance with best practices. You can accept the recommended values or make changes as you complete the form.  
* Migration: transfers your data to the target FSx for ONTAP file system
* Hot disaster recovery: ensures high availability and rapid disaster recovery for critical workloads
* Cold or archive disaster recovery: 
** Cold disaster recovery: uses longer recovery time objectives (RTO) and recovery point objects (RPO) to lower costs
** Archive: replicates data for long-term storage and compliance
* Other
+
Additionally, the use case selection determines the replication policy, or SnapMirror policy (ONTAP). The terms used to describe replication policies come from link:https://docs.netapp.com/us-en/ontap/data-protection/default-protection-policies-concept.html[ONTAP 9 documentation^]. 

** For migration and other, the replication policy is called _MirrorAllSnapshots_. _MirrorAllSnapshots_ is an asynchronous policy for mirroring all snapshots and the latest active file system.
** For hot, cold, or archive disaster recovery, the replication policy is called _MirrorAndVault_. _MirrorAndVault_ is an asynchronous and vault policy for mirroring the latest active file system and daily and weekly snapshots.
+
For all use cases, if you enable snapshots for long-term retention, the default replication policy is _MirrorAndVault_. 

.. *Tiering policy*: Select the tiering policy for the data stored in the target volume. The tiering policy defaults to the recommended tiering policy for the use case you selected.
+
_Balanced (Auto)_ is the default tiering policy when creating a volume using the workload factory console. For more information about volume tiering policies, refer to link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/volume-storage-capacity.html#data-tiering-policy[Volume storage capacity^] in AWS FSx for NetApp ONTAP documentation. Note that Workload factory uses use-case based names in the workload factory console for tiering policies and includes FSx for ONTAP tiering policy names in parentheses.
+
If you selected the migration use case, workload factory automatically selects to copy the tiering policy of source volume to the target volume. You can deselect to copy the tiering policy and select a tiering policy which applies to the volume selected for replication. 

.. *Max transfer rate*: Select *Limited* and enter the max transfer limit in MB/s. Alternatively, select *Unlimited*. 
+
Without a limit, network and application performance may decline. Alternatively, we recommend an unlimited transfer rate for FSx for ONTAP file systems for critical workloads, for example, those that are used primarily for disaster recovery. 
. Under Replication settings, provide the following: 
.. *Replication interval*: Select the frequency that snapshots are transferred from the source volume to the target volume. 
.. *Long-term retention*: Optionally, enable snapshots for long-term retention. Long-term retention enables business services to continue operating even through a complete site failure, supporting applications to fail over transparently using a secondary copy.
+
Replications without long-term retention use the _MirrorAllSnapshots_ policy. Enabling long-term retention assigns the _MirrorAndVault_ policy to the replication.
+
If you enable long-term retention, then select an existing policy or create a new policy to define the snapshots to replicate and the number to retain. 
+
NOTE: Matching source and target labels are required for long-term retention. If desired, Workload factory can create missing labels for you. 
+
* *Choose an existing policy*: select an existing policy from the dropdown menu. 
* *Create a new policy*: provide the following: 
** *Policy name*: Enter a policy name.
** Optional: Enable immutable snapshots.
*** Select *Enable immutable snapshots* to prevent snapshots taken in this policy from being deleted during the retention period.
*** Set the *Retention period* in number of hours, days, months, or years. 
** *Snapshot policies*: In the table, select the snapshot policy frequency and the number of copies to retain. You can select more than one snapshot policy. 
. Select *Create*. 

.Result
The replication relationship appears in the *Replication relationships* tab in the target FSx for ONTAP file system.  

