---
sidebar: sidebar
permalink: create-snapshot.html
keywords: create snapshot, snapshot 
summary: Create a manual snapshot of an FSx for ONTAP volume. Snapshots are point-in-time versions of your volume's content.
---
= Create a manual snapshot of an FSx for ONTAP volume
:icons: font
:imagesdir: ./media/

[.lead]
Create a manual snapshot of an FSx for ONTAP volume. Snapshots are point-in-time versions of your volume's content.

Snapshots are resources of volumes and are instant captures of your data that consume space only for modified data. Because data changes over time, snapshots usually consume more space as they get older. 

FSx for ONTAP volumes use just-in-time copy-on-write so that any unmodified files in snapshots don't consume any of the volume's capacity.

NOTE: Snapshots aren't copies of your data. If you want to make copies of your data, consider using the FSx for ONTAP backups or volume replication features. 

== Before you begin
A link is required to create a snapshot. To associate a link, click *Associate link* under *Account name*. Then return to this operation. 

.Steps
. Log in to the Workload Factory console. 
. In *Storage*, select *Go to storage inventory*. 
. In the *Volumes* tab, select the three dots menu for the volume to protect with scheduled snapshots. 
. Select *Data protection actions*, *Snapshots*, then *Create volume from a snapshot*. 
. In the Create volume from a snapshot dialog, in the *Snapshot name* field, enter a snapshot name. 
. Click *Create*. 
