---
sidebar: sidebar
permalink: create-storage-vm.html
keywords: create
summary: 
---
= Create a storage VM
:icons: font
:imagesdir: ./media/

[.lead]
You can create an FSx for ONTAP storage VM (SVM) to provide storage and data services for your workloads in Workload Factory.

== About this task
Storage VMs are isolated file servers that you can use to access the data from each workload in Workload Factory Storage. Each SVM has its own administrative credentials and endpoints for administering and accessing data. 

With SVMs, when you access data in FSx for ONTAP, your clients and workstations mount a volume, SMB share, or iSCSI LUN hosted by an SVM using the SVM's endpoint (IP address).  

== Before you begin

=== Verify the supported number of storage VMs 
Refer to the “Maximum number of SVMs per file system” table in link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/managing-svms.html#max-svms[AWS SVM documentation^]. 

.Steps
. Go to the Workload Factory console.
. In Storage, select *Go to storage inventory*. 
. Select the three dots menu for the file system to create an SVM for. 
. Select *Create storage VM*. 
. *Name*: Enter a name for the storage VM. 
. *Storage VM credentials*: 
. *Root volume security style*:  
. *Tags*: Optionally, you can add up to 50 tags.
