---
sidebar: sidebar
permalink: create-snapshot-policy.html
keywords: create
summary: "Create a custom snapshot policy for a storage VM in Workload Factory."
---
= Create a snapshot policy for storage VMs in Workload Factory
:icons: font
:imagesdir: ./media/

[.lead]
Create a custom snapshot policy for storage VMs in Workload Factory to manage snapshot creation and retention. A snapshot policy defines how the system creates snapshots for a storage VM. You can create a snapshot policy for a storage VM in an FSx for ONTAP file system. You can also share the policy across multiple storage VMs.

.About this task
You can create a custom snapshot policy that differs from the three built-in snapshot policies for FSx for ONTAP: 

* `default`
* `default-1weekly`
* `none`

By default, every volume is associated with the file system's `default` snapshot policy. We recommend using this policy for most workloads.

Customizing a policy lets you specify when to create snapshots, how many copies to retain, and how to name them.

.Before you begin 
* Once a snapshot policy is created, its association with the storage VM(s) cannot be modified, but you can always add or remove the policy from volumes.
* Consider the following about snapshot capacity before you use snapshots:
** For most datasets, an additional capacity of 20% is enough to keep snapshots for up to four weeks. As data gets older, its use for restorations becomes less likely.
** Overwriting all the data in a snapshot consumes significant volume capacity, which factors into provisioning volume capacity.
* To create a custom snapshot policy, you must associate a link. link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html[Learn how to associate an existing link or to create and associate a new link]. After the link associates, return to this operation. 

.Steps
. Log in using one of the link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html[console experiences^].
. In Storage, select *Go to storage inventory*. 
. From the Storage menu, select *FSx for ONTAP*. 
. From *FSx for ONTAP*, select the three-dot menu of the file system with the volume and then select *Manage*. 
. In the file system overview, select the *Storage VMs* tab.
. From the *Storage VMs* tab, select the three-dot menu for the volume to protect with scheduled snapshots, then *Advanced actions*, and then *Manage snapshot policies*.
. On the Snapshot policy management page, select *Create snapshot policy*. 
. In the *Snapshot policy name* field, enter a name for the snapshot policy. 
. Optionally, enter a description for the snapshot policy.
. Under *Policy schedule and copies*, select when to create snapshots. For example, every minute or hourly. 
+
You can select more than one frequency. 
. Under *Number of copies*, enter the number of copies to retain. 
+
The maximum number of copies is 1,023. 
. Optional: Under *Naming convention*, enter a *Prefix* for the policy. 
. *Retention label* is automatically populated. 
+
This label refers to the SnapMirror, or replication label that is used to select only specified snapshots for replication from the source to the target file system. 
. Optional: Enable *Immutable snapshots* for any schedules you need, set the *Retention period* for each schedule, and accept the statement to continue. 
+
Enabling immutable snapshots locks all snapshots in this snapshot policy to prevent the snapshots from being deleted during the retention period. 
. *Share across storage VMs*: Enabled by default. When enabled, the snapshot policy is shared across all storage VMs in the file system. Disable to create a snapshot policy for a single storage VM.
. Select *Create*. 

