---
sidebar: sidebar
permalink: create-volume-from-snapshot.html
keywords: create volume from snapshot, new volume
summary: Create a manual snapshot of an FSx for ONTAP volume. Snapshots are point-in-time versions of your volume's content.
---
= Create a new FSx for ONTAP volume from a snapshot
:icons: font
:imagesdir: ./media/

[.lead]
Create a new FSx for ONTAP volume from a snapshot to enable point-in-time recovery. 

.About this task
A snapshot is a read-only image of an FSx for ONTAP volume taken at a point in time. The creation of a new volume from a snapshot makes a copy of an entire volume within a few seconds independent of volume size. The newly created copy represents a new volume. 

.Before you begin
Consider the following limitations before you create a volume from a snapshot: 

* Changes to permission models: If you use this operation to switch the network-attached storage (NAS) protocol type, it might also switch the permission model that the security style provides. You might experience file access permission issues, which you can only fix manually with administrator access using the NAS client tools for permissions setting.

* Increased volume consumption: After you create a volume from a snapshot, you have two independent volumes, and both consume capacity from the host file system.

* Replication capabilities: Volumes created from a snapshot don't support volume replication.

.Steps
. Log in to the Workload Factory console. 
. In Storage, select *Go to storage inventory*.
. In the *FSx for ONTAP* tab, click the three dots menu of the file system with the volume snapshot and then select *Manage*.  
. In the file system overview, select the *Volumes* tab. 
. In the Volumes tab, click the three dots menu for the volume that has the snapshot you want to create a volume of. 
. Select *Data protection actions*, *Snapshots*, and then *Create a volume from a snapshot*. 
. In the Create volume from a snapshot dialog, enter the snapshot name. 
. Click *Create*. 

