---
sidebar: sidebar
permalink: create-storage-vm.html
keywords: create storage VM, create svm
summary: You can create an FSx for ONTAP storage VM (SVM) to provide storage and data services for your workloads in Workload Factory.
---
= Create a storage VM for an FSx for ONTAP file system
:icons: font
:imagesdir: ./media/

[.lead]
Create a storage VM (SVM) for an FSx for ONTAP file system to access storage and data services virtually for your workloads in Workload Factory.

== About this task
Storage VMs are isolated file servers that you can use to access the data from each workload in Workload Factory Storage. Each SVM has its own administrative credentials and endpoints for administering and accessing data. 

With SVMs, when you access data in FSx for ONTAP, your clients and workstations mount a volume, SMB share, or iSCSI LUN hosted by an SVM using the SVM's endpoint (IP address).  

== Before you begin
Verify the supported number of storage VMs per file system. Refer to the “Maximum number of SVMs per file system” table in link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/managing-svms.html#max-svms[AWS SVM documentation^]. 

.Steps
. Log in to the Workload Factory console.
. In Storage, select *Go to storage inventory*. 
. From the *Overview* tab, select *Create a storage VM*.
. On the Storage VM page, under Storage VM configuration, provide the following: 
. *Name*: Enter a name for the storage VM. 
. *Storage VM credentials*: Provide a password for this storage VM's `vsadmin` user or use the file system's `fsxadmin` user credentials. 
. *Root volume security style*: Select the root volume security style depending on the type of clients that access your data - UNIX (Linux clients), NTFS (Windows clients), or Mixed. 
. *Tags*: Optionally, you can add up to 50 tags.
. Click *Create*. 
