---
sidebar: sidebar
permalink: create-snapshot.html
keywords: create snapshot, snapshot 
summary: "Create a manual snapshot of an FSx for ONTAP volume in BlueXP workload factory. Snapshots are point-in-time versions of your volume's content."
---
= Create a manual snapshot of an FSx for ONTAP volume
:icons: font
:imagesdir: ./media/

[.lead]
Create a manual snapshot of an FSx for ONTAP volume in BlueXP workload factory. Snapshots are point-in-time versions of your volume's content.

Snapshots are resources of volumes and are instant captures of your data that consume space only for modified data. Because data changes over time, snapshots usually consume more space as they get older. 

FSx for ONTAP volumes use just-in-time copy-on-write so that any unmodified files in snapshots don't consume any of the volume's capacity.

NOTE: Snapshots aren't copies of your data. If you want to make copies of your data, consider using the FSx for ONTAP backups or volume replication features. 

.Before you begin
You must link:manage-links.html[associate a link] to create a snapshot. If you don't have an existing link, link:create-link.html[create a link]. To associate a link in the file system, select *Associate link* under *Account name*. Once the link associates, return to this operation. 

.Steps
. Log in using one of the link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html[console experiences^].
. In *Storage*, select *Go to storage inventory*. 
. In the *FSx for ONTAP* tab, select the three-dot menu of the file system with the volume and then select *Manage*.  
. In the file system overview, select the *Volumes* tab.
. From the *Volumes* tab, select the three-dot menu for the volume to protect. 
. Select *Data protection actions*, *Snapshots*, then *Create a snapshot*. 
. In the Create a snapshot dialog, in the *Snapshot name* field, enter a snapshot name. 
. Optional: Make the snapshot immutable to prevent the snapshot from being deleted during the retention period. 
.. Enable *Immutable snapshot*.
.. Set the *Retention period* as a number of hours, days, months, or years. 
. Select *Create*. 
