---
sidebar: sidebar
permalink: create-cyber-vault.html
keywords: create cyber vault, volume cyber vault, back up a volume
summary: "Create a cyber vault to protect data in NetApp Workload Factory."
---
= Create a cyber vault volume to protect data in NetApp Workload Factory
:icons: font
:imagesdir: ./media/

[.lead]
A cyber vault volume is an isolated, secure storage location used to store backup copies of your data, protecting it from ransomware attacks and other cyber threats. As part of vault creation, you'll create a cyber vault volume, disable all client protocols, and set up a replication relationship between the source volume and the cyber vault volume, and create immutable snapshots on the cyber vault volume.

.About this task
Replication and vault tamper proof snapshots at the edge
With additional security related modifications to scope down administrative access and disable all client protocols
This is all on a different region/network/AWS account  or more
It’s an architecture reference or a use case example

For an overview about cyber vaults, refer to the link:https://docs.netapp.com/us-en/netapp-solutions-dataops/cyber-vault/ontap-cyber-vault-overview.html[ONTAP cyber vault overview^].

.Before you begin
no prereqs?

.Steps

