---
sidebar: sidebar
permalink: create-snapshot.html
keywords: create snapshot, snapshot 
summary: Create a manual snapshot of an FSx for ONTAP volume. Snapshots are point-in-time versions of your volume's content.
---
= Create a manual snapshot of an FSx for ONTAP volume
:icons: font
:imagesdir: ./media/

[.lead]
Create a manual snapshot of an FSx for ONTAP volume. Snapshots are point-in-time versions of your volume's content.

Snapshots are resources of volumes and are instant captures of your data that consume space only for modified data. Because data changes over time, snapshots usually consume more space as they get older. 

FSx for ONTAP volumes use just-in-time copy-on-write so that any unmodified files in snapshots don't consume any of the volume's capacity.

NOTE: Snapshots aren't copies of your data. If you want to make copies of your data, consider using the FSx for ONTAP backups or volume replication features. 

== Before you begin
You must link:manage-links.html[associate a link] to create a snapshot. If you don't have an existing link, link:create-link.html[create a link]. To associate a link in the file system, click *Associate link* under *Account name*. Once the link associates, return to this operation. 

.Steps
. Log in to the Workload Factory console. 
. In *Storage*, select *Go to storage inventory*. 
. In the *FSx for ONTAP* tab, click the three dots menu of the file system with the volume and then select *Manage*.  
. In the file system overview, select the *Volumes* tab.
. From the *Volumes* tab, select the three dots menu for the volume to protect. 
. Select *Data protection actions*, *Snapshots*, then *Create volume from a snapshot*. 
. In the Create volume from a snapshot dialog, in the *Snapshot name* field, enter a snapshot name. 
. Click *Create*. 
