---
sidebar: sidebar
permalink: create-snapshot-policy.html
keywords: create
summary: "Create a snapshot policy for FSx for ONTAP volumes in BlueXP workload factory. A snapshot policy defines how the system creates snapshots for a volume."
---
= Create a snapshot policy for FSx for ONTAP volumes
:icons: font
:imagesdir: ./media/

[.lead]
Create a custom snapshot policy for FSx for ONTAP volumes in BlueXP workload factory. A snapshot policy defines how the system creates snapshots for a volume.

.About this task
You can create a custom snapshot policy that differs from the three built-in snapshot policies for FSx for ONTAP: 

* `default`
* `default-1weekly`
* `none`

By default, every volume is associated with the file system's `default` snapshot policy. We recommend using this policy for most workloads.

Customizing a policy lets you specify when to create snapshots, how many copies to retain, and how to name them.

.Before you begin 
* Consider the following about snapshot capacity before you use snapshots:
** For most datasets, an additional capacity of 20% is enough to keep snapshots for up to four weeks. As data gets older, its use for restorations becomes less likely.
** Overwriting all the data in a snapshot consumes significant volume capacity, which factors into provisioning volume capacity.
* To create a custom snapshot policy, you must link:manage-links.html[associate a link]. If you don't have an existing link, link:create-link.html[create a link]. To associate a link in the file system, select *Associate link* under *Account name*. Once the link associates, return to this operation. 

.Steps
. Log in using one of the link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html[console experiences^].
. In *Storage*, select *Go to storage inventory*. 
. In the *FSx for ONTAP* tab, select the three-dot menu of the file system with the volume and then select *Manage*.  
. In the file system overview, select the *Volumes* tab.
. From the *Volumes* tab, select the three-dot menu for the volume to protect with scheduled snapshots. 
. Select *Data protection actions*, *Snapshots*, then *Manage snapshot policies*. 
. On the Snapshot policy management page, select *Create a new snapshot policy*.
. In the *Snapshot policy name* field, enter a name for the snapshot policy. 
. Optional: in the *Description* field, enter a description for the snapshot policy.
. Under *Schedule*, select when to create snapshots. For example, every minute or hourly. 
+
You can select more than one frequency. 
. Under *Number of copies*, enter the number of copies to retain. 
+
The maximum number of copies is 1,023. 
. Optional: Under *Naming convention*, enter a *Prefix* for the policy. 
. *Retention label* is automatically populated. 
+
This label refers to the SnapMirror, or replication label, used to select only specified snapshots for replication from the source to the target file system. 
. Select *Apply*. 
