---
sidebar: sidebar
permalink: create-storage-vm.html
keywords: create storage VM, create svm
summary: "You can create an FSx for ONTAP storage VM (SVM) to provide storage and data services for your workloads in NetApp Workload Factory."
---
= Create a storage VM for an FSx for ONTAP file system
:icons: font
:imagesdir: ./media/

[.lead]
Create a storage VM (SVM) for an FSx for ONTAP file system to access storage and data services virtually for your workloads in NetApp Workload Factory.

.About this task
Storage VMs are isolated file servers that you can use to access the data from each workload in Workload Factory Storage. Each SVM has its own administrative credentials and endpoints for administering and accessing data. 

With SVMs, when you access data in FSx for ONTAP, your clients and workstations mount a volume, CIFS/SMB share, or iSCSI LUN hosted by an SVM using the SVM's endpoint (IP address).  

.Before you begin
Verify the supported number of storage VMs per file system. Refer to link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/managing-svms.html#max-svms[Managing FSx for ONTAP storage virtual machines^] in AWS documentation for the maximum number of SVMs per file system. 

== Create a storage VM

You can create a storage VM from the Workload Factory console. You can also use the following tools available in the Codebox: REST API, CloudFormation, and Terraform. link:https://docs.netapp.com/us-en/workload-setup-admin/use-codebox.html#how-to-use-codebox[Learn how to use Codebox for automation^]. 

NOTE: When using Terraform from Codebox, the code you copy or download hides `fsxadmin` and `vsadmin` passwords. You'll need to re-enter the passwords when you run the code. 

.Steps
. Log in using one of the link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html[console experiences^].
. In the Storage tile, select *Manage*.
. From the Storage menu, select *FSx for ONTAP*. 
. From *FSx for ONTAP*, select the actions menu of the file system to create a storage VM for and select *Create a storage VM*.
. On the Storage VM page, under Storage VM configuration, provide the following: 
.. *Name*: Enter a name for the storage VM. 
.. *Storage VM credentials*: Provide a password for this storage VM's `vsadmin` user or use the file system's `fsxadmin` user credentials. 
.. *Root volume security style*: Select the root volume security style depending on the type of clients that access your data - UNIX (Linux clients), NTFS (Windows clients), or Mixed. 
.. *Tags*: Optionally, you can add up to 50 tags.
. Select *Create*. 
