---
sidebar: sidebar
permalink: delete-volume.html
keywords: delete volume, volume deletion
summary: You can delete a volume in your FSx for ONTAP file system at any time. This operation is irreversible.
---
= Delete a volume
:icons: font
:imagesdir: ./media/

[.lead]
You can delete a volume in your FSx for ONTAP file system at any time. This operation is irreversible.

//Volumes with the immutable files feature cannot be deleted until the retention period expires. 

.Before you begin
Consider the following before deleting a volume: 

* Local snapshots: All snapshots associated with this FSx for ONTAP file system will be permanently deleted. 
* FSx for ONTAP backup: FSx for ONTAP backup copies will remain and you can still use them. 
* Replication relationships: We recommend that you link:delete-replication.html[delete any existing replication relationships] for this volume before deleting the volume so that no broken relationships remain. 

.Steps
. Log in to the Workload Factory console. 
. In Storage, select *Go to storage inventory*. 
. In the *FSx for ONTAP* tab, select the three dots menu of the file system with the volume to delete and then select *Manage*.
. From the file system overview, select the *Volumes* tab. 
. From the Volumes tab, select the three dots menu of the volume to delete. 
. Select *Basic actions* then *Delete volume*. 
. In the Delete volume dialog, type “delete” to delete the volume. 
. Click *Delete*. 
