---
sidebar: sidebar
permalink: delete-svm.html
keywords: delete storage vm, delete svm, remove svm
summary: Delete a storage VM (SVM) that you no longer require from an FSx for ONTAP file system configuration.
---
= Delete a storage VM
:icons: font
:imagesdir: ./media/

[.lead]
Delete a storage VM (SVM) that you no longer require from an FSx for ONTAP file system configuration.

.Before you begin
Review the following before you delete a storage VM:

* Make sure that no applications are accessing the data in the SVM. 
* Delete all non-root volumes attached to the SVM.

.Steps
. Log in to the link:https://console.workloads.netapp.com/[Workload Factory console^] 
. In Storage, select *Go to storage inventory*. 
. In the *FSx for ONTAP* tab, click the three dots menu of the file system to update and then select *Manage*.  
. From the file system overview, select the *Storage VMs* tab. 
. In the Storage VMs tab, select the three dots menu of the storage VM to configure Active Directory for.
. Select *Delete storage VM*. 
. In the Delete storage VM dialog, type “delete” to delete the storage VM. 
. Click *Delete*. 
