---
sidebar: sidebar
permalink: delete-volume.html
keywords: delete volume, volume deletion
summary: "You can delete a volume in your FSx for ONTAP file system at any time. This operation is irreversible."
---
= Delete a volume in BlueXP workload factory
:icons: font
:imagesdir: ./media/

[.lead]
You can delete a volume in your FSx for ONTAP file system at any time. This operation is irreversible. 

.Before you begin
Consider the following before deleting a volume: 

* Replication relationships: You must link:delete-replication.html[delete all existing replication relationships] for this volume before deleting the volume so that no broken relationships remain.
* Local snapshots: All snapshots associated with this FSx for ONTAP file system will be permanently deleted. 
* FSx for ONTAP backup: FSx for ONTAP backup copies will remain and you can still use them. 
* Immutable files and snapshots: Volumes containing immutable files or snapshots cannot be deleted until the retention period expires. 

.Steps
. Log in using one of the link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html[console experiences^].
. In Storage, select *Go to storage inventory*. 
. In the *FSx for ONTAP* tab, select the three-dot menu of the file system with the volume to delete and then select *Manage*.
. From the file system overview, select the *Volumes* tab. 
. From the Volumes tab, select the three-dot menu of the volume to delete. 
. Select *Basic actions* then *Delete volume*. 
. In the Delete volume dialog, do the following: 
.. Optionally, select *Back up the volume* to back up the volume before deletion.
+
The backup will remain in the file system until you manually delete it. 
.. Select *Continue*. 
.. Type “delete” to delete the volume. 
.. Select *Delete*. 
