---
sidebar: sidebar
permalink: dismiss-analysis.html
keywords: dismiss, dismiss configuration analysis, stop, optimization, FSx for ONTAP, storage
summary: "Dismiss the analysis of specific storage configurations that don't apply to your storage environment to avoid unnecessary alerts and inaccurate optimization results." 
---
= Dismiss or reactivate the analysis of storage configurations
:icons: font
:imagesdir: ./media/

[.lead]
Dismiss the analysis of specific storage configurations that don't apply to your storage environment to avoid unnecessary alerts and inaccurate optimization results. You can reactivate a dismissed configuration analysis at any time.  

.About this task
The requirements for storage configurations vary. Workload factory gives you two options for skipping the analysis of specific storage configurations so that you can monitor and get an accurate view of the health of relevant configurations. When a specific configuration analysis is dismissed, the configuration isn't included in the total optimization score.

You can dismiss and reactivate the configuration analysis at the file system level and at the volume level.

== Dismiss a configuration analysis
Dismiss to stop a configuration analysis indefinitely for an FSx for ONTAP file system or for selected volumes in a file system. You can restart the analysis when needed.

[role="tabbed-block"]
====

.Dismiss a configuration analysis for a file system
--
Dismiss to stop a configuration analysis indefinitely for an FSx for ONTAP file system. You can restart the analysis when needed. 

.Steps
. Log in using one of the link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html[console experiences^].
. In the Storage tile, select *Go to Storage inventory*.
. In the *FSx for ONTAP* tab, select the three-dot menu and then *Manage*. 
. Navigate from the FSx for ONTAP file system overview to the *Well-architected status* tab. 
. Under *Configurations*, identify the configuration you want to dismiss and select *Dismiss*.  
. Select *Dismiss* to stop the analysis for the configuration.
--

.Dismiss a configuration analysis for a volume
--

.Steps
. Log in using one of the link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html[console experiences^].
. In the Storage tile, select *Go to Storage inventory*.
. In the *FSx for ONTAP* tab, select the three-dot menu and then *Manage*. 
. Navigate from the FSx for ONTAP file system overview to the *Well-architected status* tab. 
. Under *Configurations*, identify the configuration to dismiss for selected volumes and select *View and fix*. 
. Identify the volume(s) to dismiss from the configuration analysis. 
+
* For one volume: select the three-dot menu and then select *Dismiss volume*.
* For multiple volumes: select the volumes and then select *Dismiss* next to Bulk action.
. Select *Dismiss* to stop the analysis for the configuration.
. In the Dismiss volumes dialog, select *Dismiss* to confirm.
--
====

.Result
The configuration analysis stops for the file system or selected volumes. 

You can reactivate the analysis at any time. The configuration is no longer included in the total optimization score.

== Reactivate a dismissed configuration analysis

Reactivate a dismissed configuration analysis at any time. You can select one or more configurations to reactivate.

[role="tabbed-block"]
====

.Reactivate a configuration analysis for a file system
--
.Steps
. Log in using one of the link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html[console experiences^].
. In the Storage tile, select *Go to Storage inventory*.
. In the *FSx for ONTAP* tab, select the three-dot menu and then *Manage*. 
. Navigate from the FSx for ONTAP file system overview to the *Well-architected status* tab. 
. Next to *Configurations*, select *Dismissed configurations*. 
. Identify the configuration you want to reactivate and select *Reactivate*.  

--
.Reactivate a configuration analysis for a volume
--

.Steps
. Log in using one of the link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html[console experiences^].
. In the Storage tile, select *Go to Storage inventory*.
. In the *FSx for ONTAP* tab, select the three-dot menu and then *Manage*. 
. Navigate from the FSx for ONTAP file system overview to the *Well-architected status* tab. 
. Under *Configurations*, identify the configuration to reactivate for selected volumes and select *View and fix*. 
. Identify the volume(s) to reactivate from the configuration analysis. 
+
* For one volume: select the three-dot menu and then select *Reactivate volume*.
* For multiple volumes: select the volumes and then select *Reactivate* next to Bulk action.

--
====

.Result
The configuration analysis is reactivated. A new analysis occurs daily moving forward.

