---
sidebar: sidebar
permalink: edit-volume-autogrow.html
keywords: volume autogrow, increase volume capacity, enable autogrow
summary: Enable volume autogrow to let Workload Factory manage volume capacity for you. You can disable it at any time. 
---
= Enable volume autogrow
:icons: font
:imagesdir: ./media/

[.lead]
Enable volume autogrow to let Workload Factory manage volume capacity for you. You can disable it at any time. 

Optionally, you can manually increase the volume capacity of a volume at any time using the link:increase-volume-capacity.html[increase volume capacity feature]. 

NOTE: Volume autogrow isn't supported for iSCSI volumes. 

.Before you begin
To enable volume autogrow, you must link:manage-links.html[associate a link]. If you don't have an existing link, link:create-link.html[create a link]. To associate a link in the file system, click *Associate link* under *Account name*. Once the link associates, return to this operation. 

.Steps
. Log in to the link:https://console.workloads.netapp.com/[Workload Factory console^] 
. In Storage, select *Go to storage inventory*. 
. In the FSx for ONTAP tab, select the three dots menu of the file system with the volume to update and then select *Manage*.
. From the file system overview, select the *Volumes* tab. 
. From the Volumes tab, select the three dots menu for the volume you want to modify. 
. Select *Basic actions*, then *Edit volume autogrow*. 
. In the Edit autogrow dialog, enable volume autogrow. 
. Click *Apply*.
