---
sidebar: sidebar
permalink: edit-volume-autogrow.html
keywords: volume autogrow, increase volume capacity, enable autogrow
summary: "Enable volume autogrow to let workload factory manage volume capacity for you. You can disable it at any time." 
---
= Enable volume autogrow in workload factory
:icons: font
:imagesdir: ./media/

[.lead]
Enable volume autogrow to let workload factory manage volume capacity for you. You can disable it at any time. 

Optionally, you can manually increase the volume capacity of a volume at any time using the link:increase-volume-capacity.html[increase volume capacity feature]. 

NOTE: Volume autogrow isn't supported for iSCSI volumes. 

.Before you begin
To enable volume autogrow, you must associate a link. link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html[Learn how to associate an existing link or to create and associate a new link]. After the link associates, return to this operation. 

.Steps
. Log in using one of the link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html[console experiences^].
. In Storage, select *Go to storage inventory*. 
. In the FSx for ONTAP tab, select the three-dot menu of the file system with the volume to update and then select *Manage*.
. From the file system overview, select the *Volumes* tab. 
. From the Volumes tab, select the three-dot menu for the volume you want to modify. 
. Select *Basic actions*, then *Set volume autogrow*. 
. In the Set autogrow dialog, enable volume autogrow to automatically expand the volume capacity until the volume reaches the maximum size. This feature accommodates increasing data usage, ensuring uninterrupted operations.
+
Specify the maximum volume growth size and unit. The maximum growth size cannot be smaller than the current volume size.
. Select *Apply*.
