---
sidebar: sidebar
permalink: edit-volume-autogrow.html
keywords: 
summary: 
---
= Enable volume autogrow
:icons: font
:imagesdir: ./media/

[.lead]
Enable volume autogrow to let Workload Factory manage volume capacity for you. You can disable it at any time. 

Optionally, you can manually increase the volume capacity of a volume at any time using the link:increase-volume-capacity.html[Increase volume capacity feature^]. 

NOTE: Volume autogrow isn't supported for iSCSI volumes. 

== Before you begin
To enable volume autogrow, you must associate a link. To associate a link, click *Associate link* under *Account name*. Then return to this operation.

.Steps
. Log in to the Workload Factory console. 
. In Storage, select *Go to storage inventory*. 
. Select the *Volumes* tab. 
. In the Volumes tab, select the three dots menu for the volume you want to modify. 
. Select *Basic actions*, then *Edit volume autogrow*. 
. In the Edit autogrow dialog, enable volume autogrow. 
. Click *Apply*.
