---
sidebar: sidebar
permalink: enable-snapshots-long-term.html
keywords: snapshot long-term retention, enable long-term retention
summary: "Enable snapshots for long-term retention, which lets you replicate specific snapshots for long-term disaster recovery." 
---
= Enable and edit snapshots for long-term retention
:icons: font
:imagesdir: ./media/

[.lead]
In NetApp Workload Factory, you can enable snapshots for long-term retention, which lets you replicate specific snapshots for long-term disaster recovery. 

Long-term retention enables business services to continue operating even in the event of a complete site failure, supporting transparent failover of applications using a secondary copy.

The same steps apply for enabling and editing snapshots for long-term retention.

When an on-premises ONTAP cluster is the target for the replication relationship, changing snapshots for long-term retention isn't supported. 

.Steps
. Log in using one of the link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html[console experiences^].
. In Storage, select *Go to storage inventory*. 
. From the Storage menu, select *FSx for ONTAP*. 
. From *FSx for ONTAP*, select the three-dot menu of the file system to update and then select *Manage*.  
. From the file system overview, select the *Replication relationships* tab. 
. In the Replication relationships tab, select the three-dot menu of the replication relationship schedule to change. 
. Select *Edit long-term retention*. 
. In the Edit long-term retention dialog, enable or disable snapshots for long-term retention. 
. If you select to disable snapshots for long-term retention, select *Apply* to complete this operation. 
. If you select to enable snapshots for long-term retention, choose between selecting an existing policy or creating a new policy. 
.. To use an existing policy, select it from the dropdown menu. 
.. To create a new policy, provide the following: 
... *Policy name*: Enter a policy name. 
... *Snapshot policies*: Select one or more snapshot policies. 
... *Copies to retain*: Enter the number of snapshot copies to retain on the target file system. 
. Select *Apply*. 
