---
sidebar: sidebar
permalink: explore-savings.html
keywords: cost, savings, compare costs, EBS, EFS, FSx for Windows file servers FSx for ONTAP
summary: Explore savings for your storage workloads in Amazon Elastic Block Store (EBS) storage, Elastic File System (EFS), and FSx for Windows File Servers against AWS FSx for NetApp ONTAP. 
---
= Explore savings in FSx for ONTAP 
:icons: font
:imagesdir: ./media/

[.lead]
Explore savings for your storage workloads which use Amazon Elastic Block Store (EBS), Elastic File System (EFS), and FSx for Windows File Server against FSx for NetApp ONTAP. 

Workload Factory has a built-in storage savings calculator so that you can compare your Amazon storage environments to FSx for ONTAP. You can explore savings with or without providing your AWS credentials and customize configuration settings for your storage environment. When you provide AWS credentials, you can select one or more instances of Amazon Elastic Block Store, for example, and let Workload Factory make the comparison automatically. Whether manually or automatically, the calculator determines which storage service provides the lowest cost for your storage needs. 

If the storage calculator determines that the most cost-effective storage is FSx for ONTAP, you can create or save FSx for ONTAP configurations and use the Codebox to generate Infrastructure-as-Code templates regardless of the permissions you grant to Workload Factory.

== Calculator options
Two calculator options are available for making the cost comparison between your systems and FSx for ONTAP -- customization and automatic detection for your Amazon storage environments. 

Explore savings via customization: You provide the configuration settings for a storage environment including the use case, region, number of volumes or file systems, storage amount, snapshot frequency, amount changed per snapshot, provisioned IOPS, throughput, and more. 

Explore savings for detected storage environments: Workload Factory links to your existing AWS storage environments and pulls in the details to the calculator for automatic comparison. You'll need to grant automate permissions to use automatic mode. You can change the use case, but all other details are automatically determined in the calculation. 

== Explore savings via customization
Follow the steps under the tab for your storage selection. 

[role="tabbed-block"]
====

.Amazon Elastic Block Store (EBS)
--
.Steps
. Log in to the link:https://console.workloads.netapp.com/[Workload Factory console^] 
. In Storage, select *Explore savings* then *Amazon Elastic Block Store (EBS)*. 
. In the Storage savings calculator, provide the following details: 
.. *Use case*: Required. Select a use case from the dropdown menu. The selected use case determines the FSx for ONTAP file system characteristics for comparison. 
.. *Region*: Optional. Select the region for your EBS configuration from the dropdown menu. 
.. *Select EBS volume type*: Optional. Select the EBS volume type used for your configuration.
.. *Number of volumes*: Optional. Enter the number of volumes in your EBS configuration.
.. *Storage amount per volume (TiB)*: Optional. Enter the storage amount per volume in TiB. 
.. *Snapshot frequency*: Optional. Select the snapshot frequency for your EBS configuration.  
.. *Amount changed per snapshot (GiB)*: Optional. For snapshot storage only. Enter the amount changed per snapshot in GiB. 
.. *Provisioned IOPS per volume*: Optional. For gp3, io1, and io2 volumes. Enter the provisioned IOPS per volume. 
.. *Throughput (MiB/s)*: Optional. For gp3 volumes only. Enter throughput in MiB/s per volume. 
--

.Amazon FSx for Windows File Server
--
.Steps
. Log in to the link:https://console.workloads.netapp.com/[Workload Factory console^] 
. In Storage, select *Explore savings* then *Amazon FSx for Windows File Server*.
. In the Storage savings calculator, provide the following details: 
.. *Use case*: Required. Select a use case from the dropdown menu. The selected use case determines the FSx for ONTAP file system characteristics for comparison. 
.. *Region*: Optional. Select the region for your FSx for Windows File Server configuration from the dropdown menu. 
.. *Deployment type*: Optional. Select *Single Availability Zone* or *Multiple Availability Zones*.
.. *Storage type*: SSD storage type is selected by default. 
.. *Storage capacity (TiB)*: Optional. Enter the storage capacity for the configuration. 
.. *Deduplication savings (%)*: Optional. Enter the capacity savings percentage you expect from deduplication.
.. *Snapshot frequency*: Optional. Select the snapshot frequency for your configuration.  
.. *Amount changed per snapshot (GiB)*: Optional. For snapshot storage only. Enter the amount changed per snapshot in GiB. 
.. *Provisioned SSD IOPS*: Optional. Enter the provisioned SSD IOPS. 
.. *Throughput (MiB/s)*: Optional. Enter throughput in MiB/s. 

--

.Amazon Elastic File System (EFS)
--
.Steps
. Log in to the link:https://console.workloads.netapp.com/[Workload Factory console^] 
. In Storage, select *Explore savings* then *Amazon Elastic File System (EFS)*. 
. In the Storage savings calculator, provide the following details: 
.. *Use case*: Required. Select a use case from the dropdown menu. The selected use case determines the FSx for ONTAP file system characteristics for comparison. 
.. *Region*: Optional. Select the region for your FSx for Windows File Server configuration from the dropdown menu. 
.. *File System Type*: Optional. Select *Regional* or *One zone*. 
.. *Storage capacity (TiB)*: Optional. Enter the storage capacity of the EFS configuration.
.. *Data frequently accessed (%)*: Optional. Enter the percentage of data that is frequently accessed.
.. *Throughput mode*: Optional. Select *Provisioned throughput* or *Elastic throughput*. 
.. *Throughput (MiB/s)*: Optional. Enter the throughput in MiB/s.  
--
====

After you provide details for your storage system configuration, review the calculations and recommendations provided on the page.

Additionally, scroll down to the bottom of the page to *Export PDF* or *View the calculations*.

To switch to FSx for ONTAP, follow the instructions to <<Deploy FSx for ONTAP file systems,deploy FSx for ONTAP file systems>>.

== Explore savings for detected storage environments
Follow the steps under the tab for your storage selection.

NOTE: This calculator option doesn't support calculations for EBS snapshots and FSx for Windows File Server shadow copies. When exploring savings via customization, you can provide EBS and FSx for Windows File Server snapshot details.   

[role="tabbed-block"]
====

.Amazon Elastic Block Store (EBS)
--
.Steps
. Log in to the link:https://console.workloads.netapp.com/[Workload Factory console^] 
. In Storage, select *Go to storage inventory*.  
. In the Storage inventory, select the *Elastic Block Store (EBS)* tab.
. Select the instance(s) to compare with FSx for ONTAP and click *Explore savings*.
. The Storage savings calculator appears. The following storage system characteristics are pre-filled based on the instance(s) you selected:  
.. *Use case*: The use case for your configuration. You can change the use case if needed. 
.. *Selected volumes*: the number of volumes in the EBS configuration
.. *Total storage amount (TiB)*: the storage amount per volume in TiB 
.. *Total provisioned IOPS*: for gp3, io1, and io2 volumes 
.. *Total throughput (MiB/s)*: for gp3 volumes only 
--

.Amazon FSx for Windows File Server
--
.Steps
. Log in to the link:https://console.workloads.netapp.com/[Workload Factory console^] 
. In Storage, select *Go to storage inventory*.  
. In the Storage inventory, select the *FSx for Windows File Server* tab.
. Select the instance(s) to compare with FSx for ONTAP and click *Explore savings*.
. The Storage savings calculator appears. The following storage system characteristics are pre-filled based on the deployment type of the instance(s) you selected:  
.. *Use case*: The use case for your configuration. You can change the use case if needed.
.. *Selected file systems
.. *Total storage amount (TiB)*
.. *Provisioned SSD IOPS*
.. *Throughput (MiB/s)* 

--

.Amazon Elastic File System (EFS)
--
.Steps
. Log in to the link:https://console.workloads.netapp.com/[Workload Factory console^] 
. In Storage, select *Go to storage inventory*.  
. In the Storage inventory, select the *Elastic File System (EFS)* tab.
. Select the instance(s) to compare with FSx for ONTAP and click *Explore savings*.
. The Storage savings calculator appears. The following storage system characteristics are pre-filled based on the instance(s) you selected:  
.. *Use case*: The use case for your configuration. You can change the use case if needed.
.. *Total file systems*
.. *Total storage amount (TiB)*
.. *Total provisioned throughput (MiB/s)* 
.. *Total elastic throughput - read (GiB)*
.. *Total elastic throughput – write (GiB)*
--

====

After you provide details for your storage system configuration, review the calculations and recommendations provided on the page.

Additionally, scroll down to the bottom of the page to *Export PDF* or *View the calculations*.

== Deploy FSx for ONTAP file systems
If you'd like to switch to FSx for ONTAP to realize cost savings, click *Create* to create the file system(s) directly from the Create an FSx for ONTAP file system wizard or click *Save* to save the recommended configuration(s) for later. 

Deployment methods:::
In _automate_ mode, you can deploy the FSx for ONTAP file system directly from Workload Factory. You can also copy the content from the Codebox window and deploy the system using one of the Codebox methods.
+
In  _basic_ mode, you can copy the content from the Codebox window and deploy the FSx for ONTAP file system using one of the Codebox methods.


