---
sidebar: sidebar
permalink: increase-volume-capacity.html
keywords: 
summary: 
---
= Increase volume capacity
:icons: font
:imagesdir: ./media/

[.lead]
Manually increase the volume capacity of a volume at any time. 

Optionally, you can link:edit-volume-autogrow.html[enable the autogrow feature^] to let Workload Factory manage volume capacity for you. 

== About this task
For an iSCSI LUN, this operation increases the size of the host LUN. After the capacity increases, follow the procedure provided by your host operating system to discover the new size of the LUN and expand the file system of the LUN. 

== Before you begin
To increase volume capacity, you must associate a link. To associate a link, click *Associate link* under *Account name*. Then return to this operation. 

.Steps
. Log in to the Workload Factory console. 
. In Storage, select *Go to storage inventory*. 
. Select the *Volumes* tab. 
. In the Volumes tab, select the three dots menu of the volume to increase capacity for. 
. Select *Basic actions*, then *Increase volume capacity*.
. In the Increase volume capacity dialog, provide the following:  
.. Select a larger size.
.. Change the unit if needed.  
. Click *Increase*.
