---
sidebar: sidebar
permalink: increase-volume-capacity.html
keywords: increase capacity, volume capacity
summary: Manually increase the volume capacity of a volume at any time. 
---
= Increase volume capacity
:icons: font
:imagesdir: ./media/

[.lead]
Manually increase the volume capacity of a volume at any time. 

Optionally, you can link:edit-volume-autogrow.html[enable the autogrow feature^] to let Workload Factory manage volume capacity for you. 

== About this task
For an iSCSI LUN, this operation increases the size of the host LUN. After the capacity increases, follow the procedure provided by your host operating system to discover the new size of the LUN and expand the file system of the LUN. 

== Before you begin
To increase volume capacity, you must link:manage-links.html[associate a link]. If you don't have an existing link, link:create-link.html[create a link]. To associate a link in the file system, click *Associate link* under *Account name*. Once the link associates, return to this operation. 

.Steps
. Log in to the Workload Factory console. 
. In Storage, select *Go to storage inventory*. 
. In the *FSx for ONTAP* tab, select the three dots menu of the file system with the volume to update and then select *Manage*.
. From the file system overview, select the *Volumes* tab. 
. From the Volumes tab, select the three dots menu of the volume to increase capacity for. 
. Select *Basic actions*, then *Increase volume capacity*.
. In the Increase volume capacity dialog, provide the following:  
.. Select a larger size.
.. Change the unit if needed.  
. Click *Increase*.
