---
sidebar: sidebar
permalink: increase-volume-capacity.html
keywords: increase capacity, volume capacity
summary: "Manually increase the volume capacity of a volume in NetApp Workload Factory at any time." 
---
= Increase volume capacity in NetApp Workload Factory
:icons: font
:imagesdir: ./media/

[.lead]
Manually increase the volume capacity of a volume at any time in NetApp Workload Factory. 

Optionally, you can link:edit-volume-autogrow.html[enable the autogrow feature] to let Workload Factory manage volume capacity for you. 

.About this task
For an iSCSI LUN, this operation increases the size of the host LUN. After the capacity increases, follow the procedure provided by your host operating system to discover the new size of the LUN and expand the file system of the LUN. 

.Before you begin
To increase volume capacity, you must associate a link. link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html[Learn how to associate an existing link or to create and associate a new link]. After the link associates, return to this operation.  

.Steps
. Log in using one of the link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html[console experiences^].
. In the Storage tile, select *Go to Storage*. 
. From the Storage menu, select *FSx for ONTAP*. 
. From *FSx for ONTAP*, select the actions menu of the file system with the volume to update and then select *Manage*.
. From the file system overview, select the *Volumes* tab. 
. From the Volumes tab, select the actions menu of the volume to increase capacity for. 
. Select *Basic actions*, then *Increase volume capacity*.
. In the Increase volume capacity dialog, provide the following:  
.. Select a larger size.
.. Change the unit if needed.  
. Select *Increase* to apply the change.
