---
sidebar: sidebar
permalink: initialize-replication.html
keywords: initialize replication, begin replication, start replication
summary: "Initialize a replication relationship between source and target volumes." 
---
= Initialize a replication relationship in NetApp Workload Factory
:icons: font
:imagesdir: ./media/

[.lead]
Initialize a replication relationship between source and target volumes to transfer the snapshot and all data blocks in NetApp Workload Factory. 

.About this task
Initialization performs a _baseline_ transfer: it makes a snapshot of the source volume, then transfers the snapshot and all the data blocks it references to the target volume. 

.Before you begin
Consider when you choose to complete this operation. Initialization can be time-consuming. You might want to run the baseline transfer in off-peak hours.

.Steps
. Log in using one of the link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html[console experiences^].
. In the Storage tile, select *Manage*.
. From the Storage menu, select *FSx for ONTAP*. 
. From *FSx for ONTAP*, select the actions menu of the file system to update and then select *Manage*.  
. From the file system overview, select the *Replication relationships* tab.
. In the Replication relationships tab, select the actions menu of the replication relationship to initialize. 
. Select *Initialize*. 
. In the Initialize relationship dialog, select *Initialize*. 
