---
sidebar: sidebar
permalink: known-limitations.html
keywords: limitations, fsx, ontap 
summary: "Known limitations identify platforms, devices, or functions that are not supported by this release of the product, or that do not interoperate correctly with it."
---
= Known limitations of Amazon FSx for NetApp ONTAP
:icons: font
:imagesdir: ./media/

[.lead]
Known limitations identify platforms, devices, or functions that are not supported by this release of the product, or that do not interoperate correctly with it. Review these limitations carefully. 

== Region support
The following AWS regions are not supported:

* China regions
* GovCloud (US) regions
* Secret Cloud
* Top Secret Cloud

== Adding HA pairs limitations
* This operation might take approximately 30 minutes to complete.
* Adding HA pairs limits the following operations: adding more HA pairs, provisioning IOPS, increasing SSD capacity, and updating throughput capacity. 

== Throughput capacity region support

=== Scale-up deployments
Scale-up configurations are supported up to 2 GB/s in all regions. The following regions support up to 4 GB/s maximum throughput capacity for scale-up deployments: US East (Ohio) Region, US East (N. Virginia) Region, US West (Oregon) Region, and Europe (Ireland).

=== Scale-out deployments
The following regions support up to 6 GB/s maximum throughput capacity for scale-out deployments: US East (N. Virginia and Ohio), US West (N. California and Oregon), Europe (Frankfurt, Ireland, and Stockholm), and Asia Pacific (Singapore and Sydney).

== Capacity management
* The volume autogrow feature isn't currently supported for the iSCSI protocol. 
* When the automatic capacity management feature is running, manual capacity increase isn't allowed. 
* Disabling the automatic capacity management feature is only possible with the same permissions used to enable it. 
* When automatic capacity management is enabled, a link is required to make sure volume inodes increase along with storage capacity. 

== Storage VMs
The number of storage VMs is limited per SKU. Creating storage VMs beyond the limitation isn't supported in Workload Factory.^1^ 

Refer to link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/managing-svms.html#max-svms[Managing FSx for ONTAP storage virtual machines^] in AWS documentation for the maximum number of SVMs per file system. 

== iSCSI protocol support
* The iSCSI protocol is only available for FlexVol volumes. ^1^  
* Only a single LUN can be configured per volume.
* Volume size decreases aren't supported for iSCSI volumes.

== Data protection
* Snapshots cannot be deleted. 
* When you replicate a file system, all volumes in the file system use the same replication policy.
* For long-term retention replication relationships, only the last snapshot is available for restore.
* The following features aren't supported with immutable snapshots:
** Consistency groups
** FabricPool
** FlexCache volumes
** SMtape
** SnapMirror active sync
** SnapMirror policy rules using the -schedule parameter
** SnapMirror synchronous
** SVM data mobility (used for migrating or relocating an SVM from a source cluster to a destination cluster)

== Storage savings calculator
The Storage savings calculator doesn't calculate cost savings for the following configurations: 

* FSx for Windows File Server: HDD storage type
* Elastic Block Store (EBS): st1, sc1, and standard volume types
* Elastic File System (EFS): Bursting throughput mode

== System Manager  
System Manager doesn't support links for FSx for ONTAP connectivity. 

== AWS Secrets Manager support 
AWS Secrets Manager isn't supported when using a Console agent.

== Amazon S3 access points limitation

The limit for the number of S3 access points per storage VM is 4,000.


Note:

. Applies to Amazon FSx for NetApp ONTAP