---
sidebar: sidebar
permalink: known-limitations.html
keywords: limitations, fsx, ontap 
summary: Known limitations identify platforms, devices, or functions that are not supported by this release of the product, or that do not interoperate correctly with it. Review these limitations carefully.
---
= Known limitations
:icons: font
:imagesdir: ./media/

[.lead]
Known limitations identify platforms, devices, or functions that are not supported by this release of the product, or that do not interoperate correctly with it. Review these limitations carefully.

== Operational modes
_Read_ mode isn't currently available. 

== Link
A link is required to complete some operations like replication in the Workload Factory user interface. 

== Storage efficiency
Storage efficiency cannot be disabled or enabled after volume creation. 

== Capacity management
* The volume autogrow feature isn't currently supported for the iSCSI protocol. 
* When the automatic capacity management feature is running, manual capacity increase isn't allowed. 
* Disabling the automatic capacity management feature is only possible with the same permissions used to enable it. 

== Storage VMs
The number of storage VMs is limited per SKU. Creating storage VMs beyond the limitation isn't supported in Workload Factory. Refer to link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/managing-svms.html#max-svms[Managing FSx for ONTAP storage virtual machines^] for the maximum number of SVMs per file system. 

== iSCSI protocol support
* The iSCSI protocol is only supported for scale-up deployments.
* The iSCSI protocol is only available for FlexGroup volumes. 
* Only a single LUN can be configured per volume. 

== Region support
* *Option 1 without footnote*: Canada West (Calgary) region isn't currently supported in Workload Factory.
* *Option 2 with footnote*: Canada West (Calgary) region isn't currently supported.footnote:[Applies to Workload Factory] 

== Data protection
* Snapshots cannot be deleted. 
* Only replication between FSx for ONTAP file systems is supported.
* When you replicate a file system, all volumes in the file system use the same replication policy. 
* Only the last snapshot is available for restore.  

== Storage savings calculator
The Storage savings calculator doesn't calculate cost savings for the following configurations: 

* FSx for Windows File Server: HDD storage type
* Elastic Block Store (EBS): st1, sc1, and standard volume types
* Elastic File System (EFS): Bursting throughput mode


