---
sidebar: sidebar
permalink: learn-fsx-ontap.html
keywords: Amazon FSx for NetApp ONTAP, FSx, storage, aws
summary: Amazon FSx for NetApp ONTAP is a fully managed service allowing customers to launch and run file systems as the storage backend for your workloads within Workload Factory. 
---
= Learn about Amazon FSx for NetApp ONTAP 
:icons: font
:imagesdir: ./media/

[.lead]
Amazon FSx for NetApp ONTAP is a fully managed service allowing customers to launch and run file systems as the storage backend for your workloads within Workload Factory. 

FSx for ONTAP is the _Storage_ component in Workload Factory.

link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html[Refer to Amazon FSx for NetApp ONTAP documentation^]. 

== Features
FSx for ONTAP provides the same features, performance, and administrative capabilities NetApp customers use on premises today, with the simplicity, agility, security, and scalability of a native AWS service.

* No need to configure or manage storage devices, software, or backups.
* Support for CIFS, iSCSI, NFSv3, NFSv4.x, and SMB v2.0 - v3.1.1 protocols.
* Low cost, virtually unlimited data storage capacity using available Infrequently Accessed (IA) storage tier.
* Certified to run on latency-sensitive applications including Oracle RAC.
* Choice of bundled and pay-as-you-go pricing.

== Additional features in Workload Factory

* Storage cost comparison calculator: Compares your AWS Elastic File System (EFS), Elastic Block Storage (EBS), and FSx for Windows File Server storage costs with AWS FSx for ONTAP. From the calculator, you can view how FSx storage configurations offer potential savings and plan your move to FSx storage.
* Workload Factory user interface: Provides *Quick create* and *Advanced create* deployment mode options. Quick create includes AWS, NetApp, and industry standard best practices for your storage configurations.
* Codebox: The Codebox is an Infrastructure as Code feature that gives developers code templates, such as for creating a file system, for use outside Workload Factory. 

== Tools to access
The following tools access FSx for ONTAP:

* User interface: 
* Codebox: 

== Cost


== Supported regions

https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/[View supported Amazon regions.^]

== Getting help
Amazon FSx for NetApp ONTAP is an AWS first-party solution. For questions or technical support issues associated with your FSx for ONTAP file system, infrastructure, or any solution using this service, use the Support Center in your AWS Management Console to open a support case with AWS. Select the “FSx for ONTAP” service and appropriate category. Provide the remaining information required to create your AWS support case.

For general questions about Workload Factory or Workload Factory applications and services, you can start with ?.