---
sidebar: sidebar
permalink: limit-transfer-rate.html
keywords: limit max transfer rate, limit transfer rate
summary: "Limit the max transfer rate of a replication relationship. An unlimited transfer rate might negatively impact the performance of other applications and your network." 
---
= Limit the max transfer rate of a replication relationship
:icons: font
:imagesdir: ./media/

[.lead]
Limit the max transfer rate of a replication relationship. An unlimited transfer rate might negatively impact the performance of other applications and your network. 

.About this task
Limiting the max transfer rate is optional but recommended. Without a limit, network and application performance may decline. 

Alternatively, we recommend an unlimited transfer rate for FSx for ONTAP file systems for critical workloads, for example, those that are used primarily for disaster recovery. 

.Before you begin
Consider how much bandwidth to allocate for replication.

.Steps
. Log in using one of the link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html[console experiences^].
. In Storage, select *Go to storage inventory*. 
. In the *FSx for ONTAP* tab, select the three-dot menu of the file system to update and then select *Manage*.  
. From the file system overview, select the *Replication relationships* tab. 
. In the Replication relationships tab, select the three-dot menu of the replication relationship to limit the max transfer rate for. 
. Select *Edit max transfer rate*. 
. In the Edit max transfer rate dialog, select *Limited* and enter the max transfer limit in MB/s. 
+
Alternatively, select *Unlimited*.
. Select *Apply*. 
