---
sidebar: sidebar
permalink: links-overview.html
keywords: links, accounts, lambda
summary: "A Workload Factory link creates a trust relationship and connectivity between a Workload Factory account and one or more FSx for ONTAP file systems."
---

= Learn about NetApp Workload Factory links
:icons: font
:imagesdir: ./media/

[.lead]
A NetApp Workload Factory link creates a trust relationship and connectivity between a Workload Factory account and one or more FSx for ONTAP file systems. This allows you to monitor and manage certain file system features directly from the ONTAP REST API calls that are not available through the Amazon FSx for ONTAP API.

You don't need a link to get started with Workload Factory, but in some cases you'll need to create a link to unlock all Workload Factory features and workload capabilities. 

== Why links are beneficial
Links are beneficial because they allow Workload Factory to perform operations that are not natively available through the Amazon FSx for ONTAP API. Links enable advanced ONTAP capabilities and automations, which enhance the management of FSx for ONTAP file systems.

Here are some benefits of using links:
 
* The link enables the NetApp Console to send ONTAP commands directly to your FSx for ONTAP file system, bringing advanced ONTAP features beyond what AWS offers natively.
* Links leverage AWS Lambda to execute code in response to events. This serverless approach removes the dependency of an instance running in your VPC.

== How links work

Links leverage AWS Lambda. Lambda executes code in response to events and automatically manages the computing resources required by that code. The links that you create are part of your NetApp account and they are associated with an AWS account.

After creating a link, you can associate it with one, or many, FSx for ONTAP file systems. Each file system can be associated only to one link in the same NetApp account. If you have multiple NetApp accounts, a single file system can be associated with additional links under different NetApp accounts.

You create and associate links from the Storage workload in Workload Factory. 

You can authenticate links using credentials stored in the Workload Factory credentials service or with your credentials stored in AWS Secrets Manager. Workload factory doesn't support changing authentication modes.

== Costs

Each transaction that Lambda performs incurs a charge. Because Lambda acts as a proxy between the two systems, there is a charge when Lambda sends a request to the ONTAP REST API on a file system, and when it sends the response back to Workload Factory.

link:https://aws.amazon.com/lambda/pricing/[Learn more about the costs related to using AWS Lambda^]

== When a link is required

Workload factory requires a link to display some information and to perform some tasks. If you attempt to perform an operation that requires a link and you haven't associated a link with the FSx for ONTAP file system, Workload Factory notifies you that the operation requires a link. 

The features that require a link include:

* Well-architected status of FSx for ONTAP file system configurations for proactive maintenance, reliability, and cost-performance optimization
* NetApp Autonomous Ransomware Protection (ARP/AI)
* Enhanced holistic capacity observability across FSx for ONTAP file systems
* Volume and storage VM data replication, management, and monitoring
* SMB/CIFS shares and NFS export policy provisioning and management
* Management of iSCSI volumes on an FSx for ONTAP file system
* Creation and management of snapshot policies for custom protection SLA
* Inode management enhancements for automatic capacity management
* Volume autogrow for elastic scaling
* Clone creation and management, for instant, in-place, data cloning
* Displaying additional metrics directly from ONTAP such as the ONTAP version

Learn how to link:create-link.html[connect a link to an FSx for ONTAP file system]. 