
= Manage snapshot policies

*Does a user need to associate a link to manage all of the following for snapshot policies?*

== Change a snapshot policy

== Assign a snapshot policy

.Before you begin
You must link:manage-links.html[associate a link] to assign a snapshot policy. If you don't have an existing link, link:create-link.html[create a link]. To associate a link in the file system, select *Associate link* under *Account name*. Once the link associates, return to this operation. 

.Steps
. Log in using one of the link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html[console experiences^].
. In *Storage*, select *Go to storage inventory*. 
. In the *FSx for ONTAP* tab, select the three-dot menu of the file system with the volume and then select *Manage*.  
. In the file system overview, select the *Volumes* tab.
. From the *Volumes* tab, select the three-dot menu for the volume to protect. 
. Select *Data protection actions*, *Snapshots*, then *Assign snapshot policy*. 
. In the Assign snapshot policy dialog, select a snapshot policy to assign to the volume and review the policy schedule. 
+
If the policy retains immutable snapshots, and you'd like to use it, accept the statement. *I don't understand how this works. Hanan, can you explain how a policy contains immutable snapshot retention?*
. Select *Assign*. 

.Result
The snapshot policy has been assigned to the volume. 

== Enable immutable snapshots

.Before you begin
You must link:manage-links.html[associate a link] to assign a snapshot policy. If you don't have an existing link, link:create-link.html[create a link]. To associate a link in the file system, select *Associate link* under *Account name*. Once the link associates, return to this operation. 

.Steps
. Log in using one of the link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html[console experiences^].
. In *Storage*, select *Go to storage inventory*. 
. In the *FSx for ONTAP* tab, select the three-dot menu of the file system with the volume and then select *Manage*.  
. In the file system overview, select the *Volumes* tab.
. From the *Volumes* tab, select the three-dot menu for the volume to protect. 
. Select *Data protection actions*, *Snapshots*, then *Make a snapshot immutable*. 
. In the Make a snapshot immutable dialog, do the following: 
.. *Snapshot name*: Select the snapshot to make immutable.  
.. Set the *Retention period* in number of hours, days, months, or years. 
.. Accept the statement. 
. Select *Apply*. 

.Result
The snapshot is now immutable.

== Delete a snapshot policy