---
sidebar: sidebar
permalink: manage-immutable-files.html
keywords: enable immutable files, disable immutable files, lock files, unlock files
summary: Make your files permanently immutable with the immutable files feature. 
---
= Manage immutable files
:icons: font
:imagesdir: ./media/

[.lead]
Make your files permanently immutable with the immutable files feature. This feature prevents files from being accidentally or maliciously deleted or modified. 

.About this task
Enabling the immutable files feature permanently commits files in this volume to an immutable WORM (write-once-read-many) state. 

Enabling this feature is possible only during volume creation. 

Once enabled, this feature cannot be disabled. 

Retention modes:::
You can select from two retention modes - Enterprise or Compliance. 

* In Enterprise mode, an immutable files, or SnapLock, administrator can delete a file during its retention period. 
* In Compliance mode, a WORM file cannot be deleted before its retention period expires. Similarly, the immutable volume cannot be deleted until the retention periods for all files within the volume expire. 

Autocommit:::
You'll have the option to enable the autocommit feature. The autocommit feature commits a file to WORM state on a SnapLock volume if the file did not change for the autocommit period duration. The autocommit feature is disabled by default. The files you want to autocommit must reside on a SnapLock volume.

== Enable the immutable files feature
Follow the steps to enable the immutable files features for any volume. 

.Before you begin
Consider the retention mode and retention period for the files in the volume before you begin. 

.Steps
. Log in to the link:https://console.workloads.netapp.com/[Workload Factory console^]. 
. In Storage, select *Go to storage inventory*. 
. Select the *Volumes* tab. 
. In the Volumes tab, select the three dots menu of the volume to clone. 
. Select *Data protection actions*, then *Manage immutable files*. 
. Enable the immutable files feature. 
. Click *Apply*. 
. In the Enable immutable files dialog, read and accept the notice. 
. Click *Enable*. 
. On the Manage Immutable files page, enable *Immutable files powered by SnapLock*. 
. Under *Retention mode*, select *Enterprise* or *Compliance*. 
. Under *Retention period*, select *Unspecified* or *Specify period*. 
+
Unspecified: The default minimum period is "0" years and the default maximum period is "30 years". 
. If you selected *Specify period*, provide the following details: 
.. *Retention period*: This period must be greater than or equal to the minimum retention period and less than or equal to the maximum retention period. 
.. *Minimum and maximum periods*: Set the minimum and maximum periods to commit files in this volume to an immutable WORM state. 
. Under *Autocommit*, enable or disable the feature to automatically commit files to WORM that haven't been modified during the Autocommit period. 
. Under *Privileged delete*, enable or disable the feature. Enabling the feature allows a SnapLock administrator to delete an unexpired WORM volume. This feature is only supported in Enterprise retention mode. 
. Under *Volume append mode*, enable or disable the feature. Enabling volume append mode enables you to add new content to WORM files. 
. Click *Apply*. 

// Disabling the feature is currently unavailable. Add if it becomes available. - Rachel Lithman

//== Disable the immutable files feature
//Disabling immutable files allows volumes to be modified or deleted.

//Follow the steps to disable the immutable files features for any volume. 

//.Steps
//. Log in to the link:https://console.workloads.netapp.com/[Workload Factory console^]. 
//. In Storage, select *Go to storage inventory*. 
//. Select the *Volumes* tab. 
//. In the Volumes tab, select the three dots menu of the volume to clone. 
//. Select *Data protection actions*, then *Manage immutable files*. 
//. Disable *Immutable files powered by SnapLock*.
//. In the Disable immutable files dialog, read and accept the statement. 
//. Click *Disable*.
//. On the Manage immutable files page, click *Apply*. 
