---
sidebar: sidebar
permalink: manage-snapshots.html
keywords: snapshot, snapshots, manage snapshots, edit snapshots, access snapshots, delete snapshots, remove snapshots 
summary: "Edit snapshot settings, enable directory access, and delete snapshots to manage your snapshots and data protection in Workload Factory."
---
= Manage snapshots of an FSx for ONTAP volume
:icons: font
:imagesdir: ./media/

[.lead]
Edit snapshot settings, enable directory access, and delete snapshots to manage your snapshots and data protection in Workload Factory. 

== Edit a snapshot
Edit the name, label, and retention period of a snapshot. If the snapshot isn't already immutable, you can make the snapshot immutable. 

.Steps
. Log in using one of the link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html[console experiences^].
. In *Storage*, select *Go to storage inventory*.  
. From the Storage menu, select *FSx for ONTAP*. 
. From *FSx for ONTAP*, select the three-dot menu of the file system with the volume and then select *Manage*.  
. In the file system overview, select the *Volumes* tab.
. From the *Volumes* tab, select the three-dot menu for the volume with the snapshot to edit.
. Select *Data protection actions* and then *Manage snapshots*. 
. From the Manage snapshots page, select the three-dot menu for the snapshot to edit, and then select *Edit*.
. In the Edit a snapshot dialog, you may edit the following: 
.. Change the name. 
.. Change the label. 
.. Change the retention period. 
.. Optional: *Make this snapshot immutable* to prevent the snapshot from being deleted during the retention period. 
+
If the snapshot is already immutable, you can't edit this setting.
+
Accept the statement regarding immutable snapshots.
. Select *Apply*. 

== Access a snapshot
Enable snapshot directory access to give users the ability access snapshots autonomously.

.Steps
. Log in using one of the link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html[console experiences^].
. In *Storage*, select *Go to storage inventory*.  
. From the Storage menu, select *FSx for ONTAP*. 
. From *FSx for ONTAP*, select the three-dot menu of the file system with the volume and then select *Manage*.  
. In the file system overview, select the *Volumes* tab.
. From the *Volumes* tab, select the three-dot menu for the volume with the snapshot to access.
. Select *Data protection actions* and then *Manage snapshots*. 
. From the Manage snapshots page, select the three-dot menu for the snapshot to access, and then select *Access*.
. In the Access snapshot dialog, select to *Enable snapshot directory access* to access this volume snapshot and all snapshots of the volume.

* For NFS volumes: Select *NFS access path* to view the NFS path for the snapshot.
* For SMB/CIFS volumes: Select *SMB access path* to view the SMB path for the snapshot.
. Copy the access path.
. Select *Apply*. 

== Restore data from a snapshot
You have the option to restore data from a snapshot to an existing volume or to a new volume.

link:https://review.docs.netapp.com/us-en/workload-fsx-ontap_snapshot-mgmt/restore-volume-from-snapshot.html[Restore a volume from a snapshot]

== Delete a snapshot
Delete a snapshot to free up space.

Immutable snapshots cannot be deleted until the retention period ends. 

.Steps
. Log in using one of the link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html[console experiences^].
. In *Storage*, select *Go to storage inventory*.  
. From the Storage menu, select *FSx for ONTAP*. 
. From *FSx for ONTAP*, select the three-dot menu of the file system with the volume and then select *Manage*.  
. In the file system overview, select the *Volumes* tab.
. From the *Volumes* tab, select the three-dot menu for the volume with the snapshot to delete.
. Select *Data protection actions* and then *Manage snapshots*. 
. From the Manage snapshots page, select the three-dot menu for the snapshot to delete, and then select *Delete*.
. In the Delete snapshot dialog, type "delete".
. Select *Delete* to confirm deletion.

.Related information

* link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-snapshot.html[Create a snapshot] 
* link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-snapshot-policy.html[Create a snapshot policy]
* link:https://docs.netapp.com/us-en/workload-fsx-ontap/restore-volume-from-snapshot.html[Restore a volume from a snapshot]

