---
sidebar: sidebar
permalink: manage-cifs-share.html
keywords: cifs, smb, SMB/CIFS, cifs share, change, update, modify, delete, create
summary: "Managing a volume's SMB/CIFS share in Workload Factory includes creation, determining user and group access, and deletion." 
---
= Manage the SMB/CIFS share for a volume in Workload Factory
:icons: font
:imagesdir: ./media/

[.lead]
Managing a volume's SMB/CIFS share in Workload Factory includes SMB/CIFS share creation, determining the users and groups to give access to and the level of permissions to give them, and SMB/CIFS share deletion.

.Before you begin
Before you begin, do the following: 

* To manage SMB/CIFS shares, you must associate a link. link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html[Learn how to associate an existing link or to create and associate a new link]. After the link associates, return to this operation. 
* Determine the users or groups to give access to and the level of permissions to give them. 

== Create an SMB/CIFS share for a volume
Follow the steps to create an SMB/CIFS share for a volume. 

.Steps
. Log in using one of the link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html[console experiences^].
. In Storage, select *Go to Storage*.
. From the Storage menu, select *FSx for ONTAP*. 
. From *FSx for ONTAP*, select the three-dot menu of the file system with the volume to update and then select *Manage*.
. From the file system overview, select the *Volumes* tab. 
. From the Volumes tab, select the three-dot menu of the volume to change the SMB share for. 
. Select *Advanced actions*, then *Manage SMB/CIFS shares*. 
. On the Manage SMB/CIFS shares page, select *Create SMB/CIFS share*.
. In the Create SMB/CIFS share dialog, provide the following: 
.. *Name*: Enter the name of the SMB/CIFS share.
.. *Path*: Either define the path using the default volume name or provide a share to an internal directory. 
+
Valid path inputs for volume name, for example "avocado", are as follows:
+
** /avocado
** /avocado/folder
** /avocado/folder/subfolder
** /avocado/file-name
+
Valid path inputs for share name, for example "Server", are as follows:

** \\Server
** \\Server\Projects
** \\Server\Projects\Shared resources
.. *Permissions*: Select Full control, Read/Write, Read, or No access, and then enter the users or groups separated by a semicolon ( ; ). Users or groups are case sensitive and the user's domain must be included using the format "domain\username".  
. Select *Create*. 

== Change an SMB/CIFS share for a volume
Follow the steps to change the SMB/CIFS share settings for a volume.

.Steps
. Log in using one of the link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html[console experiences^].
. In Storage, select *Go to Storage*.
. In the *FSx for ONTAP* tab, select the three-dot menu of the file system with the volume to update and then select *Manage*.
. From the file system overview, select the *Volumes* tab. 
. From the Volumes tab, select the three-dot menu of the volume to change the SMB share for. 
. Select *Advanced actions*, then *Manage SMB/CIFS shares*. 
. On the Manage SMB/CIFS shares page, select *View and edit*.
. Change the SMB/CIFS access permissions, or the users or groups to give permissions to. 
+
Changes might cause current users or groups to lose access to the SMB/CIFS share.
. Select *Apply* to save the changes.

== Delete an SMB/CIFS share for a volume
Follow the steps to delete an SMB/CIFS share for a volume.

.Steps
. Log in using one of the link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html[console experiences^].
. In Storage, select *Go to Storage*.
. In the *FSx for ONTAP* tab, select the three-dot menu of the file system with the volume to update and then select *Manage*.
. From the file system overview, select the *Volumes* tab. 
. From the Volumes tab, select the three-dot menu of the volume to change the SMB share for. 
. Select *Advanced actions*, then *Manage SMB/CIFS shares*. 
. On the Manage SMB/CIFS shares page, select the three-dot menu of the SMB/CIFS share and then select *Delete*. 
+
Deleting the SMB/CIFS share makes it unavailable and inaccessible to any users who want to mount it.
. In the Delete SMB/CIFS share dialog, select *Delete* to confirm deletion.