---
sidebar: sidebar
permalink: manage-immutable-files.html
keywords: enable immutable files, disable immutable files, lock files, unlock files
summary: You can update certain immutable files settings when the feature is enabled.  
---
= Manage immutable files for a volume in NetApp Workload Factory
:icons: font
:imagesdir: ./media/

[.lead]
You can update certain immutable files settings for a volume when the feature is enabled, such as the retention policy and periods, the autocommit period, and volume append mode.

Note that enabling immutable files is only possible during link:create-volume.html[volume creation].

.Steps
. Log in using one of the link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html[console experiences^].
. In the Storage tile, select *Manage*. 
. From the Storage menu, select *FSx for ONTAP*. 
. From *FSx for ONTAP*, select the actions menu of the file system with the volume to update and then select *Manage*. 
. In the Volumes tab, select the actions menu of the volume to clone. 
. Select *Data protection actions*, then *Manage immutable files*.
. On the Manage Immutable files page, you can update the following:  
* *Retention period*: select *Unspecified* or *Specify period*. 
+
** *Unspecified*: The default minimum period is "0" years and the default maximum period is "30 years".
** *Specify period*: Option to define the retention policy, minimum and maximum periods, the autocommit feature, and the volume append mode feature. Provide the following details: 
*** *Retention policy*: This period must be greater than or equal to the minimum retention period and less than or equal to the maximum retention period. 
*** *Minimum and maximum periods*: Set the minimum and maximum periods to commit files in this volume to an immutable WORM state. 
* *Autocommit*: enable or disable the feature to automatically commit files to WORM that haven't been modified during the Autocommit period.
* *Privileged delete*: Enable or disable the feature. Enabling the feature allows a SnapLock administrator to delete an unexpired WORM volume. This feature is only supported in Enterprise retention mode. 
* *Volume append mode*: enable or disable the feature. Enabling volume append mode enables you to add new content to WORM files. 
. Click *Apply*. 

.Result
The updates now apply to the volume. 