---
sidebar: sidebar
permalink: manage-cifs-share.html
keywords: cifs, CIFS, cifs share, change cifs share, update cifs share, modify cifs share
summary: "Change the CIFS share for a volume in BlueXP workload factory that uses the SMB/CIFS protocol type." 
---
= Manage the CIFS share for a volume in BlueXP workload factory
:icons: font
:imagesdir: ./media/

[.lead]
Managing a volume's CIFS share in BlueXP workload factory involves determining the users and groups to give access to and the type of access to give them.

.Before you begin
Determine the users or groups to give access to and the type of access to give them. 

.Steps
. Log in using one of the link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html[console experiences^].
. In Storage, select *Go to storage inventory*.
. In the *FSx for ONTAP* tab, select the three-dot menu of the file system with the volume to update and then select *Manage*.
. From the file system overview, select the *Volumes* tab. 
. From the Volumes tab, select the three-dot menu of the volume to change the SMB share for. 
. Select *Advanced actions*, then *Edit CIFS share*. 
. On the Edit CIFS share page, provide the following: 
.. *Name*: Enter the name of the CIFS share.
.. *Permissions*: Select Full control, Read/Write, Read, or No access, and then enter the users or groups separated by a semicolon ( ; ). Users or groups are case sensitive and the user's domain must be included using the format "domain\username". 
. Select Apply. 
+
Changes may cause current users or groups to lose access to the CIFS share. 
. Select *Continue* to save the changes. 

.Result
Changes to the CIFS share are applied. 
