---
sidebar: sidebar
permalink: manage-svm-tags.html
keywords: edit storage vm tags, vm tags, svm tags
summary: "Add, update, or remove storage VM tags for a storage VM at any time." 
---
= Manage storage VM tags in NetApp Workload Factory
:icons: font
:imagesdir: ./media/

[.lead]
Tags can help you categorize your resources. You can add, edit, and remove tags for a storage VM at any time in NetApp Workload Factory. 

.Steps
. Log in using one of the link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html[console experiences^].
. In the Storage tile, select *Go to Storage*. 
. From the Storage menu, select *FSx for ONTAP*. 
. From *FSx for ONTAP*, select the actions menu of the file system with the storage VM to update and then select *Manage*.
. In the file system overview under Storage VMs, select *Manage*.
. From the Manage storage VMs screen, select the actions menu of the storage VM to edit tags for, then select *Basic actions* > *Edit storage VM tags*. 
. On the Edit storage VM tags page, add, edit, or remove tags. 
+
The maximum number of tags you can apply to a storage VM is 50.
. Select *Apply*. 
