---
sidebar: sidebar
permalink: modify-snapshot-policy.html
keywords: modify, edit, change
summary: 
---
= Modify a snapshot policy for an FSx for ONTAP file system
:icons: font
:imagesdir: ./media/

[.lead]
Update a snapshot schedule for an FSx for ONTAP file system at any time.  

== Before you begin
To modify a snapshot policy, another snapshot policy must exist. If you don't have another snapshot policy, link:create-snapshot-policy.html[create a new snapshot policy for this volume], and then return to this operation.

You must have a link to display existing snapshot policies. link:https://review.docs.netapp.com/us-en/workload-setup-admin_first-draft/manage-links.html[Create the link^] and then you'll be able to modify a snapshot policy. 

.Steps
. Go to the Workload Factory console. 
. In Storage, select *Go to storage inventory*.  
. In the *Volumes* tab, select the three dots menu for the volume of which to change the snapshot policy.
. Select *Data protection actions* then *Manage snapshot policies*. 
. On the Snapshot policy management page select *Change an existing snapshot policy*.
. In the *Snapshot policy name* field, select a different snapshot policy for this volume.
+ 
If no other snapshot policies exist, link:create-snapshot-policy.html[create a new snapshot policy for this volume], and then return to this step. 
. Click *Apply*. 
