---
sidebar: sidebar
permalink: provision-iops.html
keywords: iops, SSD, provision, allocate
summary: "Automatically provision or manually provision SSD IOPS for an FSx for ONTAP file system." 
---
= Provision SSD IOPS for an FSx for ONTAP file system
:icons: font
:imagesdir: ./media/

[.lead]
Automatically provision or manually provision SSD IOPS for an FSx for ONTAP file system in NetApp Workload Factory. 

.About this task
You can enable automatic SSD IOPS provisioning for an FSx file system or manually provision IOPS. 

Automatically provisioned IOPS are calculated as three IOPS per GiB. 

If you manually provision IOPS, you might need to increase IOPS before link:increase-file-system-capacity.html[increasing file system capacity]. 

For information about IOPS limits, refer to link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/limits.html[Quotas^] in AWS FSx for NetApp ONTAP documentation. 

.Steps
. Log in using one of the link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html[console experiences^].
. In the Storage tile, select *Go to Storage*. 
. From the Storage menu, select *FSx for ONTAP*. 
. From *FSx for ONTAP*, select the three-dot menu of the file system to provision IOPS for and then select *Manage*. 
. Under Information, select the pencil icon that appears next to the dropdown arrow when the mouse hovers over the *IOPS allocation* row. 
. In the Provisioned IOPS dialog, select *Automatic* or *User provisioned*. 
. If you select *User provisioned*, enter the desired *IOPS value*. 
. Select *Apply*. 
