---
sidebar: sidebar
permalink: ransomware-protection.html
keywords: ransomware, arp, autonomous protection, ai, arp ai, security, detect, detection, threat, attack, suspect, anti-ransomware, entropy, abnormal volume activity, antiransomware, extension conformity, ransomware protection strategy
summary: "NetApp Autonomous Ransomware Protection with Artificial Intelligence uses workload analysis in NAS environments to detect and warn about abnormal activity that might be a ransomware attack."  
---
= Enable Autonomous Ransomware Protection with AI for a file system
:icons: font
:imagesdir: ./media/

[.lead]
NetApp Autonomous Ransomware Protection with AI (ARP/AI) uses workload analysis in NAS environments to detect and warn about abnormal activity that might be a ransomware attack. When an attack is suspected, ARP also creates new, immutable snapshots in addition to the existing protection provided by scheduled snapshots.

== How ARP/AI works

ARP/AI protects against denial-of-service attacks where the attacker withholds data until a ransom is paid. ARP/AI offers real-time ransomware detection based on: 

* Identification of the incoming data as encrypted or plaintext.
* Analytics that detect:
+
** **Entropy**: An evaluation of the randomness of data in a file
** **File extension types**: An extension that does not conform to the normal extension type
** **File IOPS**: A surge in abnormal volume activity with data encryption (beginning with ONTAP 9.11.1)

ARP can detect the spread of most ransomware attacks after only a small number of files are encrypted, take action automatically to protect data, and alert you that a suspected attack is happening.

NOTE: No ransomware detection or prevention system can completely guarantee safety from a ransomware attack. Although it's possible an attack might go undetected, ARP/AI acts as an important additional layer of defense if anti-virus software has failed to detect an intrusion.

=== Learning and active modes
ARP/AI operates first in _learning mode_ and then automatically switches to _active mode_. 

.Learning mode
When you enable ARP/AI it runs in _learning mode_. In learning mode, the FSx for ONTAP file system develops an alert profile based on the analytic areas: entropy, file extension types, and file IOPS. After the file system runs ARP/AI in learning mode for enough time to assess workload characteristics, workload factory automatically switches to ARP/AI to _active mode_ and starts protecting your data.

.Active mode
After ARP switches to _active mode_, FSx for ONTAP creates ARP/AI snapshots to protect the data if a threat is detected.

In active mode, if a file extension is flagged as abnormal, you should evaluate the alert. You can act on the alert to protect your data or you can mark the alert as a false positive. Marking an alert as a false positive updates the alert profile. For example, if the alert is triggered by a new file extension and you mark the alert as a false positive, you will not receive an alert the next time that file extension is observed. 

== How to recover data after a ransomware attack

When an attack is suspected, the system takes a volume snapshot at that point in time and locks that copy. If the attack is confirmed later, the volume can be restored using the ARP/AI snapshot.

Locked snapshots cannot be deleted until the retention period ends. However, if you decide later to mark the attack as a false positive, the locked copy will be deleted. 

With the knowledge of the affected files and the time of attack, it is possible to selectively recover the affected files from various snapshots rather than simply reverting the whole volume to one of the snapshots.

link:?

== Before you begin

== Steps

