---
sidebar: sidebar
permalink: rebalance-volume.html
keywords: rebalance capacity, volume capacity, redistribute capacity
summary: "Check and rebalance the capacity of a volume to avoid imbalances that develop over time."
---
= Check and rebalance a volume's capacity
:icons: font
:imagesdir: ./media/

[.lead]
Check the balance of FlexVol or FlexGroup volume capacity and rebalance volume capacity to spread files evenly across all FlexVol volumes in a node or across all constituents so that all nodes participate in the workload of a single FlexGroup volume.

.About this task
Rebalancing volume capacity is supported for FlexVol volumes and FlexGroup volumes. Rebalancing a volume redistributes the capacity when imbalances develop over time due to the addition of new files and file growth. After you manually start the rebalance operation, we select the files and move them automatically and non-disruptively. Volume transfer operations consume file system resources.

Each volume type and rebalancing operations differ as follows.

FlexVol volumes:::
FlexVol volumes are logical containers that offer flexibility in managing data, allowing for expansion, contraction, movement, and efficient copying. They can be used with NAS and SAN environments. 
+
A FlexVol volume can be balanced in relation to other FlexVol volumes within one node in an FSx for ONTAP file system. If the file system has only a single FlexVol volume, then rebalancing isn't possible. When the file system has more then one FlexVol volume per node and a single FlexVol volume is selected, the FlexVol volume is balanced in the context of all FlexVols but only the selected volume is allowed to move.

FlexGroup volumes::: 
FlexGroup volumes, on the other hand, are scalable NAS containers designed for high performance and automatic load distribution. They consist of multiple member volumes (constituents) that share traffic transparently. FlexGroup volumes provide massive capacity, exceeding FlexVol limits, with up to 60PB capacity and 400 billion files. They simplify management by offering a single namespace container.
+
Capacity is spread across a number of constituents in a scale-out FSx for ONTAP file system with two or more high availability (HA) pairs. Each constituent is a container that dictates the maximum single file size. FSx for ONTAP spreads files across all constituents in an even way so all nodes participate in the workload of a single FlexGroup volume.
+
When the constituents aren't distributed evenly across all nodes, FlexGroup volume performance decreases. 
+
Checking the balance of FlexGroup volume capacity includes assessing the current layout of constituents. When you rebalance the volume's capacity, BlueXP workload factory designs a new constituent layout with an even number of constituents to spread the data evenly across all HA pairs. The service executes the rebalance plan which in turn improves read and write operations.

NOTE: Rebalancing isn't supported for SAN volumes like iSCSI and NVMe.

== Check the balance of your volumes 
Check the balance of FlexVol or FlexGroup volumes in an FSx for ONTAP file system. 

.Before you begin
* FlexGroup volume balance is available only for FSx for ONTAP file systems using a scale-out deployment with at least two HA pairs.
* To check the balance of a volume, you must link:manage-links.html[associate a link]. If you don't have an existing link, link:create-link.html[create a link]. To associate a link in the file system, select *Associate link* under *Account name*. After the link associates, return to this operation.  

.Steps
. Log in using one of the link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html[console experiences^].
. In *Storage*, select *Go to storage inventory*. 
. In the *FSx for ONTAP* tab, select the three-dot menu of the file system that contains volumes to rebalance and then select *Manage*.
. From the file system overview, select the *Volumes* tab. 
. From the Volumes tab, select *Check volume balance* at the top of the table.
. In the Volume balance window, review the balance status of:

* FlexGroup volumes
* FlexVol volumes  
+
When a volume is unbalanced, consider <<Rebalance a volume,rebalancing it>>.

== Rebalance a volume
Rebalance one or more unbalanced volumes. 

NOTE: A workload factory admin can <<Stop a volume rebalance operation,stop rebalancing>> during the operation.

.Before you begin
* <<Check the balance of your volumes,Check the balance of a volume>> before rebalancing volumes.
* To rebalance a volume, you must link:manage-links.html[associate a link]. If you don't have an existing link, link:create-link.html[create a link]. To associate a link in the file system, select *Associate link* under *Account name*. After the link associates, return to this operation. 
* Note that existing snapshots on volumes you rebalance become partial and cannot be used to restore volume data, but new snapshots taken after rebalancing can be used to restore volume data. 
* FlexVol volumes are best rebalanced altogether to balance all volume resources evenly. Deselected volumes don't actively participate in the balancing procedure.

[role="tabbed-block"]
====
.FlexVol volume
--
A FlexVol volume can be balanced in relation to other FlexVol volumes within one node in an FSx for ONTAP file system. When the file system has more then one FlexVol volume per node and a single FlexVol volume is selected, then the FlexVol volume is balanced in the context of all FlexVols but only the selected volume is allowed to move.

.Steps
. Log in using one of the link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html[console experiences^].
. In *Storage*, select *Go to storage inventory*. 
. In the *FSx for ONTAP* tab, select the three-dot menu of the file system that contains the volume to rebalance and then select *Manage*.
. From the file system overview, select the *Volumes* tab. 
. From the Volumes tab, select *Check volume balance* at the top of the table.
. In the Volumes balance window, optionally select *Data distribution* in the FlexVol balance summary to view used capacity per aggregate.
. Select *Rebalance* to rebalance one or more unbalanced volumes. 
. In the Rebalance wizard, follow the steps. 
.. *Max transfer rate*: Optional. Disabled by default. Enable throttling to limit the bandwidth of a volume move on your file system and to slow outgoing volume replication traffic. 
+
Enter the throttle value in MB/s.
+ 
Select *Next*.
.. Review the current and proposed layouts of all FlexVol volumes, and then select *Next*. 
.. Carefully review what will happen and the note before beginning the rebalance operation.
. Select *Rebalance*. 

.Result
The FlexVol volume is rebalanced. When the operation completes, the file system will be throttled back to the original value. 
--
.FlexGroup volume
--
Data redistributes across member volumes to rebalance the FlexGroup volume. Based on your chosen layout, the rebalance operation might add FlexGroup member volumes and increase the size of provisioned volumes. 

.Steps
. Log in using one of the link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html[console experiences^].
. In *Storage*, select *Go to storage inventory*. 
. In the *FSx for ONTAP* tab, select the three-dot menu of the file system that contains the volume to rebalance and then select *Manage*.
. From the file system overview, select the *Volumes* tab. 
. From the Volumes tab, select *Check FlexGroup balance* at the top of the table.
. In the FlexGroup balance window, select *Rebalance* to rebalance one or more unbalanced volumes. 
. In the Rebalance wizard, select the data distribution layout that you prefer.
+
* *Performance-optimized* (recommended): increases the number of FlexGroup member volumes and the provisioned size of the volume. Follows NetApp best practice.
* *Restricted*: supports volumes in a replication relationship. The number of FlexGroup member volumes and the size of provisioned volumes remains the same. Selected by default if all selected volumes participate in a replication relationship.
* *Manual*: Select the desired number of FlexGroup member volumes per HA pair. Depending on your selection, the number of FlexGroup member volumes and the provisioned size of the volume might increase. 
. *Throttling*: Optional. Disabled by default. Enable throttling to limit the bandwidth of a volume move on your file system and to slow outgoing volume replication traffic. 
+
Enter the throttle value in MB/s.
. Select a layout comparison view and then select *Next*. 
+
* Volume layout comparison
* FSx for ONTAP layout comparison

. Optionally, download a list of volume moves before rebalancing. 
. Select *Rebalance*. 

.Result
FlexGroup member volumes are moved one at a time during rebalancing. When the operation completes, the file system will be throttled back to the original value.
--

====

== Stop a volume rebalance operation

Stop a rebalance operation at any time; it isn't disruptive. Stopping the operation aborts active volume moves.

You can start another rebalance operation later. 

.Steps
. After you begin the rebalance operation, from the Volume balance page, select *Stop rebalancing*.

. In the Stop rebalancing dialog, select *Stop*.

.Result

The volume rebalance operation stops and active volume moves abort.  