---
sidebar: sidebar
permalink: rebalance-volume.html
keywords: rebalance capacity, volume capacity, redistribute capacity
summary: Rebalance the capacity of a volume to avoid imbalances that develop over time.
---
= Rebalance a volume's capacity
:icons: font
:imagesdir: ./media/

[.lead]
Rebalance the capacity of a volume to avoid imbalances that develop over time. 

== About this task
Rebalancing a volume redistributes the capacity when imbalances develop over time due to the addition of new files and file growth. After you manually start the rebalance operation, we select the files and move them automatically and non-disruptively. 

NOTE: Rebalancing a volume is only supported for FlexGroup volumes. 

== Before you begin
To rebalance a volume, you must associate a link. To associate a link, click *Associate link* under *Account name*. Then return to this operation. 

.Steps
. Log in to the Workload Factory console. 
. In *Storage*, select *Go to storage inventory*. 
. Select the *Volumes* tab. 
. In the *Volumes* tab, select the three dots menu of the volume to rebalance.
. Select *Advanced actions*, then *Rebalance volume*. 
. In the Rebalance volume dialog, select *Rebalance*. 
