---
sidebar: sidebar
permalink: rebalance-volume.html
keywords: rebalance capacity, volume capacity, redistribute capacity
summary: "Rebalance the capacity of a volume to avoid imbalances that develop over time."
---
= Rebalance a volume's capacity in BlueXP workload factory
:icons: font
:imagesdir: ./media/

[.lead]
Rebalance the capacity of a volume to avoid imbalances that develop over time. 

.About this task
Rebalancing a volume redistributes the capacity when imbalances develop over time due to the addition of new files and file growth. After you manually start the rebalance operation, we select the files and move them automatically and non-disruptively. 

NOTE: Rebalancing a volume is only supported for FlexGroup volumes. 

.Before you begin
To rebalance a volume, you must link:manage-links.html[associate a link]. If you don't have an existing link, link:create-link.html[create a link]. To associate a link in the file system, select *Associate link* under *Account name*. Once the link associates, return to this operation.  

.Steps
. Log in using one of the link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html[console experiences^].
. In *Storage*, select *Go to storage inventory*. 
. In the *FSx for ONTAP* tab, select the three-dot menu of the file system that contains the volume to rebalance and then select *Manage*.
. From the file system overview, select the *Volumes* tab. 
. From the Volumes tab, select the three-dot menu of the volume to rebalance.
. Select *Advanced actions*, then *Rebalance volume*. 
. In the Rebalance volume dialog, select *Rebalance*. 
