---
sidebar: sidebar
permalink: replicate-svm-to-file-system.html
keywords: 
summary: Replicating a storage VM to another FSx for ONTAP file system provides a protective layer of data access in case of data loss. 
---
= Replicate a storage VM to another FSx for ONTAP file system
:icons: font
:imagesdir: ./media/

[.lead]
Replicating a storage VM to another FSx for ONTAP file system provides a protective layer of data access in case of data loss. This operation replicates all volumes in one storage VM to another FSx for ONTAP file system. 

.Before you begin
To replicate a storage VM to another FSx for ONTAP file system, you must link:manage-links.html[associate a link]. If you don't have an existing link, link:create-link.html[create a link]. To associate a link in the file system, click *Associate link* under *Account name*. Once the link associates, return to this operation. 

.Steps
. Log in to the link:https://console.workloads.netapp.com/[Workload Factory console^] 
. In Storage, select *Go to storage inventory*. 
. In the *FSx for ONTAP* tab, select the three dots menu of the file system with the storage VM to replicate and then select *Manage*.
. From the file system overview, select the *Storage VMs* tab.
. From the Storage VMs tab, select the three dots menu of the storage VM to replicate an SVM for.
. Select *Replicate storage VM*. 
. On the Create replication page, under Replication target, provide the following: 
.. *FSx for ONTAP file system*: Select credentials, region, and FSx for ONTAP file system name for the target FSx for ONTAP file system.
.. *Storage VM name*: Select the storage VM from the dropdown menu.
.. *Volume name*: The target volume name is generated automatically with the following format `{OriginalVolumeName}_copy`.
.. *Tiering policy*: Select the tiering policy for the data stored in the target volume. 
+
_Auto_ is the default tiering policy when creating a volume using the Workload Factory FSx for ONTAP user interface. For more information about volume tiering policies, refer to link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/volume-storage-capacity.html#data-tiering-policy[Volume storage capacity^]in AWS FSx for NetApp ONTAP documentation. 
.. *Max transfer rate*: Select *Limited* and enter the max transfer limit in MB/s. Alternatively, select *Unlimited*. 
+
Without a limit, network and application performance may decline. Alternatively, we recommend an unlimited transfer rate for FSx for ONTAP file systems for critical workloads, for example, those that are used primarily for disaster recovery. 
. Under Replication settings, provide the following: 
.. *Replication interval*: Select the frequency that snapshots are transferred from the source volume to the target volume. 
.. *Long-term retention*: Optionally, enable snapshots for long-term retention. 
+
If you enable long-term retention, then select an existing policy or create a new policy to define the snapshots to replicate and the number to retain.  
+
... For *Choose an existing policy*, select an existing policy from the dropdown menu. 
... For *Create a new policy*, provide the following: 
.... *Policy name*: Enter a policy name. 
.... *Snapshot policies*: In the table, select the snapshot policy frequency and the number of copies to retain. You can select more than one snapshot policy. 
. Click *Create*. 

.Result
All volumes within the storage VM are replicated to the target file system. 



