---
sidebar: sidebar
permalink: replicate-svm-to-file-system.html
keywords: 
summary: Replicate a storage VM to another FSx for ONTAP file system. 
---
= Replicate a storage VM to another FSx for ONTAP file system
:icons: font
:imagesdir: ./media/

[.lead]
Replicate a storage VM to another FSx for ONTAP file system. 

== About this task
Replicating a storage VM to another FSx for ONTAP file system provides a protective layer of data access in case of data loss. 

== Before you begin
To replicate a storage VM to another FSx for ONTAP file system, you must associate a link. To associate a link, click *Associate link* under *Account name*. Then return to this operation. 

.Steps
. Log in to the Workload Factory console. 
. In Storage, select *Go to storage inventory*. 
. Select the three dots menu for the file system to replicate an SVM for.
. Select *Replicate storage VM*. 
. Under FSx for ONTAP file system, select the credentials and region for the target FSx for ONTAP file system. 
. Then, select the target FSx for ONTAP file system for replication. 
. Under Storage VM name, provide a name for the replicated storage VM. 
. Under Volume name, select the volume? – Look at the stage environment.

