---
sidebar: sidebar
permalink: reset-svm-password.html
keywords: reset storage vm password, reset svm password
summary: "Reset the password for a storage VM in NetApp Workload Factory when necessary." 
---
= Reset the storage VM password in NetApp Workload Factory
:icons: font
:imagesdir: ./media/

[.lead]
Reset the password for a storage VM in NetApp Workload Factory when necessary. 

.Steps
. Log in using one of the link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html[console experiences^].
. From Storage, select *Go to Storage*. 
. From the Storage menu, select *FSx for ONTAP*. 
. From *FSx for ONTAP*, select the three-dot menu of the FSx for ONTAP file system with the storage VM to update and then select *Manage*. 
. From the Overview tab of the file system, select the *Storage VMs* tab. 
. In the Storage VMs tab, select the three-dot menu of the storage VM to reset the password for.
. Select *Reset password*. 
. In the Reset password dialog, provide the following: 
.. *New password*: Enter a new password for the storage VM. 
.. *Confirm password*: Enter the new password again to confirm. 
. Select *Apply*. 
