---
sidebar: sidebar
permalink: restore-volume-from-snapshot.html
keywords: restore volume, snapshot
summary: "Restore an FSx for ONTAP volume from a snapshot when the volume contains deleted or corrupted files." 
---
= Restore a volume from a snapshot in workload factory
:icons: font
:imagesdir: ./media/

[.lead]
In workload factory, you can restore an FSx for ONTAP volume from a snapshot when the volume contains deleted or corrupted files. 

.About this task
This operation restores data from a snapshot to a new volume. 

.Before you begin
You can only restore a volume from a snapshot if you have an existing snapshot copy of the volume. 

Make sure you have enough capacity to complete this operation. 

.Steps
. Log in using one of the link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html[console experiences^].
. In *Storage*, select *Go to storage inventory*.  
. In the *FSx for ONTAP* tab, select the three-dot menu of the file system with the volume and then select *Manage*.  
. In the file system overview, select the *Volumes* tab.
. From the *Volumes* tab, select the three-dot menu for the volume to restore from a snapshot.
. Select *Data protection actions* and then *Manage snapshots*. 
. From the Manage snapshots page, select the three-dot menu for the snapshot to restore, and then select *Restore*.
. In the Restore volume from a snapshot dialog, select to *Restore as a new volume*.
. In the *Restored volume name* field, enter a unique name for the volume to restore. 
. Select *Restore*. 
