---
sidebar: sidebar
permalink: split-cloned-volume.html
keywords: split clone volume, FlexVol volume
summary: Split a clone FlexVol volume from its parent volume to make the clone a normal read-write FlexVol volume. 
---
= Split a cloned volume
:icons: font
:imagesdir: ./media/

[.lead]
Split a clone FlexVol volume from its parent volume to make the clone a normal read-write FlexVol volume. 

Data is accessible on the clone and the parent during the split. The split process only updates metadata and requires minimal IO. No data blocks are copied.

.About this task 
The clone splitting operation involves the following: 

* New snapshot copies of the FlexClone volume cannot be created during the split operation.
* A FlexClone volume cannot be split from the parent volume if it belongs to a data protection relationship.
* If you take the FlexClone volume offline while splitting is in progress, the split operation is suspended; when you bring the FlexClone volume back online, the splitting operation resumes.
* After the split, both the parent FlexVol volume and the clone require the full space allocation determined by their volume guarantees.
* After a FlexClone volume is split from its parent the two cannot be rejoined.

.Before you begin
Consider the following before you split a cloned volume: 

* To split a cloned volume, you must link:manage-links.html[associate a link]. If you don't have an existing link, link:create-link.html[create a link]. To associate a link in the file system, click *Associate link* under *Account name*. Once the link associates, return to this operation.  
* You must be a cluster administrator.
* The FlexClone volume must be online when the split operation begins.
* The parent volume must be online for the split to succeed.

.Steps
. Log in to the Workload Factory console. 
. In Storage, select *Go to storage inventory*. 
. Select the *Volumes* tab. 
. In the Volumes tab, select the three dots menu of the volume with the cloned volume to split. 
. Select *Data protection actions*, then *Split cloned volume*. 
. In the Split volume dialog, click *Delete*. 
