---
sidebar: sidebar
permalink: stop-replication.html
keywords: stop replication, break replication
summary: Stop a replication relationship between source and target volumes. 
---
= Stop a replication relationship
:icons: font
:imagesdir: ./media/

[.lead]
Stop a replication relationship between source and target volumes. 

== About this task
When you stop a replication, scheduled replication updates from the source volume to the target volume pause. The target volume transitions from read-only to read-write. 

.Steps
. Log in to the Workload Factory console. 
. In Storage, select *Go to storage inventory*. 
. In the *FSx for ONTAP* tab, click the three dots menu of the file system to update and then select *Manage*.  
. From the file system overview, select the *Replication relationships* tab. 
. In the Replication relationships tab, click the three dots menu of the replication relationship to stop. 
. Select *Break*. 
. In the Break replication dialog, select *Break*.

The replication status of the volume changes to *Broken*. The target volume becomes writable.