---
sidebar: sidebar
permalink: update-throughput-capacity.html
keywords: update throughput, change throughput, throughput capacity
summary: "Update throughput capacity for an FSx for ONTAP file system in NetApp Workload Factory as needed." 
---
= Update throughput capacity for a file system
:icons: font
:imagesdir: ./media/

[.lead]
Update throughput capacity for an FSx for ONTAP file system in NetApp Workload Factory as needed. 

For throughput capacity limits, refer to link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/limits.html[Quotas^] in AWS FSx for NetApp ONTAP documentation.

.Steps
. Log in using one of the link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html[console experiences^].
. In the Storage tile, select *Manage*.
. From the Storage menu, select *FSx for ONTAP*. 
. From *FSx for ONTAP*, select the actions menu of the file system to update throughput capacity for and then select *Manage*. 
. Under Information, select the pencil icon next to *Throughput capacity*. The pencil icon appears next to the drop down arrow when the mouse hovers over the *Throughput capacity* row. 
. In the Throughput capacity dialog, select the throughput capacity you need. 
. Select *Apply* to save the changes. 