---
sidebar: sidebar
permalink: view-volume-details.html
keywords: volume details, volume information
summary: View volume details, distribution, consumption, access, and protection.
---
= View volume details
:icons: font
:imagesdir: ./media/

[.lead]
View volume details, distribution, consumption, access, and protection. 

Volume details appear only after a volume has been created in a file system.

.Steps
. Log in to the link:https://console.workloads.netapp.com/[Workload Factory console^]. 
. In Storage, select *Go to storage inventory*. 
. In the Volumes tab, select the three dots menu for the volume you wish to modify. 
. Select *Basic actions* then *View volume details*. 
. In *Volume details*, select the tabs to view the following volume details: 
.. *General details*: includes volume name, volume UUID, volume ID, creation time, state, volume type (read-write/data protection (RW/DP) or read only), snapshot policy name, hosting storage VM (SVM), and tags. 
.. *Distribution*: includes hosting aggregates, volume style (FlexGroup or FlexVol), constituents (FlexGroup only), and rebalance ratio (FlexGroup only -high, medium, or low).
.. *Consumption*: includes size, SSD used, capacity pool used, autogrow setting, max growth size, storage efficiency setting, compression space saved, deduplication space saved, tiering policy, and cooling days.
.. *Access*: includes junction path, security style, export policy and NFS version for NFS, and Active Directory, CIFS share name, users or groups, and permissions for SMB/CIFS, and initiator group and host IQNs for iSCSI.
.. *Protection*: includes local snapshot, snapshot policy name, remote replication, and FSx for ONTAP backup.
