---
sidebar: sidebar
permalink: whats-new.html
keywords: what's new, features, new, release notes, enhancements, fixes, new features, workload factory, amazon fsx
summary: Learn what's new with Amazon FSx for NetApp ONTAP.
---
= What's new
:icons: font
:imagesdir: ./media/

[.lead]
Learn what's new with Amazon FSx for NetApp ONTAP.

== 4 August

=== Terraform support 
You can now use Terraform from the Codebox to deploy and manage file systems and storage VMs. 

* link:create-file-system.html[Create a file system]
* link:create-storage-vm.html[Create a storage VM]
* link:https://docs.netapp.com/us-en/workload-setup-admin/use-codebox.html[Use Terraform from Codebox^]

=== Throughput and IOPS recommendations in the storage calculator   
The storage calculator makes FSx for ONTAP file system configuration recommendations for throughput and IOPS based on AWS best practices, which provides you with optimal guidance for your selections.  

== 7 July
Amazon FSx for NetApp ONTAP is now generally available in BlueXP Workload Factory. 

link:learn-fsx-ontap.html[Learn about BlueXP Workload Factory for Amazon FSx for NetApp ONTAP].
