---
sidebar: sidebar
permalink: whats-new.html
keywords: what's new, features, new, release notes, enhancements, fixes, new features, workload factory, amazon fsx
summary: Learn what's new with Amazon FSx for NetApp ONTAP.
---
= What's new
:icons: font
:imagesdir: ./media/

[.lead]
Learn what's new with Amazon FSx for NetApp ONTAP.

== 4 August 2024

=== Terraform support 
You can now use Terraform from the Codebox to deploy and manage file systems and storage VMs. 

* link:create-file-system.html[Create a file system]
* link:create-storage-vm.html[Create a storage VM]
* link:https://docs.netapp.com/us-en/workload-setup-admin/use-codebox.html[Use Terraform from Codebox^]

=== Throughput and IOPS recommendations in the storage calculator   
The storage calculator makes FSx for ONTAP file system configuration recommendations for throughput and IOPS based on AWS best practices, which provides you with optimal guidance for your selections.

== 7 July 2024

=== Initial release of Workload Factory for Databases
The initial release includes the capability to explore savings with Amazon FSx for NetApp ONTAP as the storage environment for your database workloads, detect, manage, and deploy Microsoft SQL Servers, deploy and clone databases, and monitor these jobs within Workload Factory.
