=== Link creation updates    

* Codebox viewer: Codebox is now integrated in the link creation process. You can view the CloudFormation template from the Codebox in Workload Factory before redirecting to AWS to execute the operation.  

* Required permissions: The permissions required to execute the link creation in AWS CloudFormation are now available to view and copy from the Create Link wizard in Workload Factory.

* Support for manual link creation: This feature allows standalone creation in AWS CloudFormation with manual registration of the link ARN. It's useful when a security or DevOps team assists in the link creation process.  

link:https:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.adoc[Create a link^]

=== Tab views in storage inventory
Your storage inventory has been updated to a two-tab view: 

* FSx for ONTAP: displays the FSx for ONTAP file systems you currently have.
* Explore savings: displays Elastic Block Store, FSx for Windows File Server, and Elastic File Systems storage systems. From there, you can explore savings for these systems by comparing them with FSx for ONTAP. 

