=== Cache volume management
You can perform the following cache volume management operations from within the Workload Factory console:

* Edit the cache name
* Increase the capacity of a cache volume
* Edit the mount path or export policy for a cache volume
* Change the caching method, or mode, for a cache volume
* Prepopulate a cache volume
* Delete a cache volume

link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-cache-volumes.html[Manage cache volumes^]

=== Automatic inode management available    
You can now enable automatic inode management without the need to enable automatic capacity management. 

link:https://docs.netapp.com/us-en/workload-fsx-ontap/enable-auto-capacity-management.html[Enable automatic inode management^]

=== Threshold warning setting for capacity and inode usage
You can now set threshold warnings for both capacity and inode usage when enabling automatic capacity or inode management. This allows for more granular monitoring and alerting based on your specific needs. To use this setting, you'll need to configure notifications using the link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html[NetApp Workload Factory notification service^]. 

=== Volume size decrease available
You can now decrease the size of NFS and SMB/CIFS volumes in NetApp Workload Factory. This feature allows for better management of storage resources by enabling you to reduce the size of volumes that are no longer needed at their current capacity.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/adjust-volume-capacity.html[Decrease the capacity of a volume^]

=== Enhanced FSx for ONTAP resource state
Workload Factory has enhanced the "misconfigured" resource state to include an explanation of the actual issue for the resource.

=== _Analysis_ menu item added

The new _Analysis_ menu item has been added to the Storage menu. This menu item provides quick access to the analysis of events that show on your file systems. 

=== Well-architected analysis updates
Workload factory analyzes your FSx for ONTAP file systems for the following configurations: 

* Delete unnecessary snapshots: checks whether volumes have outdated and unnecessary snapshots that can be deleted to reduce costs. 
* Volume utilization nearing full: checks whether any volumes are using 80% or more of their file capacity. This helps you identify volumes that may need additional capacity.




