=== Enhancements to Replication relationships tab   

We've added several new columns to the replication relationships table to give you more information about your replication relationships in the *Replication relationships* tab. The table now includes the following columns:

* SnapMirror policy
* Source file system
* Target file system
* State of the relationship (healthy, failed, or initializing)
* Last transfer time

=== Well-architected analysis updates

Workload factory now analyzes your FSx for ONTAP file systems for the following configurations: 

* Long-term retention data reliability: checks whether labels assigned to the snapshot policy of source volume are identical to the labels assigned to the long-term retention policy. When labels are identical, data replication is reliable between source and destination volumes.
* File capacity thresholds: checks whether the file capacity thresholds are set to 80% or lower. This helps you avoid running out of space on your file systems.
* NetApp Autonomous Ransomware Protection with AI (ARP/AI): checks whether ARP/AI is enabled on your file systems. This feature helps you detect and recover from ransomware attacks.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html[View the well-architected status of your FSx for ONTAP file systems]

=== Dismiss a configuration from the well-architected analysis
You can now dismiss one or more configurations from the well-architected analysis. This allows you to ignore specific configurations that you don't want to address at the moment.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html[Dismiss a configuration from the well-architected analysis]

=== Terraform support for link creation

You can now use Terraform from the Codebox to create a link for association with an FSx for ONTAP file system. This functionality is for users who create links manually. 

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html[Connect to an FSx for ONTAP file system with a Lambda link]
