=== Support for on-premises data replication using an S3 access point

Workload Factory supports replicating on-premises ONTAP data to the cloud for integration with AWS GenAI, ML, and analytics. You can replicate your on-premises data to an NFS or SMB/CIFS volume using an S3 access point.

link:create-replication.adoc[Replicate on-premises ONTAP data to the cloud using an S3 access point]

=== Well-architected analysis updates
Workload Factory analyzes your FSx for ONTAP file systems for the following configurations: 

* NetApp Autonomous Ransomware Protection (ARP/AI) disabled includes block devices: checks whether ARP/AI is disabled on block device volumes
* Cache relationship write mode: checks whether the write mode is optimal for the cache volume workload
* Unnecessary backup deletion: checks whether backups are outdated or unnecessary that can be deleted to reduce costs

link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html[View the well-architected status of your FSx for ONTAP file systems]

=== Home page integration

The Workload Factory console home page embeds the Ask me AI assistant so that you can ask questions and learn more about Workload Factory without leaving the Workload Factory console. The redesigned home page displays Storage, Databases, and VMware tiles with details about workload resources and easy navigation to the respective workloads. The new *Focus* tile displays any FSx for ONTAP EMS events and well-architected issues for storage and database workloads that require your attention.

=== Analysis navigation change
Previously, the Analysis tab was accessible from an FSx for ONTAP file system overview. With the new navigation, the *Analysis* tab has moved to the Storage menu on the left side of the Workload Factory console. 