=== VS Code extension available for FSx for ONTAP

The VS Code extension for Amazon FSx for NetApp ONTAP, "netapp-fsx-ontap", allows you to access and manage your FSx for ONTAP file system resources. With the extension, you can use Secure Shell (SSH) to connect to the terminal with EC2 Instance Connect or connect directly from your computer. GitHub Copilot is integrated with the extension. You can ask GitHub Copilot questions about your resources and take actions without using the Workload Factory console or ONTAP CLI.

=== Support for ONTAP S3 endpoints

With this feature, you can create volumes using S3 endpoints, or access points, from the Workload Factory console. Using an S3 access point, you can access file data residing on SMB/CIFS or NFS volumes via the AWS S3 APIs. This allows you to integrate your existing data with GenAI, ML, and analytics from AWS services that support S3 access points.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-volume.html[Create a volume]

=== Optimize savings in the Storage calculator for Amazon Elastic Block Store (EBS) 

Workload Factory can analyze your EBS performance usage and then suggest the best and most cost-efficient FSx for ONTAP configuration so that you can save more by switching to FSx for ONTAP.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/explore-savings.html#explore-savings-for-detected-storage-environments[Explore savings for detected storage environments in the Workload Factory console]

=== Quick access to resource screen from file system inventory

You can quickly navigate to an FSx for ONTAP file system resource screen by selecting the file system name, now a hyperlink, from the FSx for ONTAP inventory.

=== Discover cache relationships in the Workload Factory console

If you have _FlexCache_, or _cache_, relationships in an FSx for ONTAP file system, you can discover and view them from the Workload Factory console. This allows you to better understand data flows, optimize cache utilization, and improve efficiency across distributed environments.

=== Well-architected analysis updates

==== Additional analyses 
Workload factory now analyzes your FSx for ONTAP file systems for the following configurations: 

* Unauthorized access to volume: checks whether clients allow NAS access to volumes as well as access using the iSCSI protocol. Only one type of access should be permitted. 
* Volume file capacity utilization threshold: checks whether the file capacity thresholds are set to 80% or lower. This helps you avoid running out of space on your file systems.
* Volume utilization nearing full: checks whether any volumes are using 80% or more of their file capacity. This helps you identify volumes that may need additional capacity.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html[View the well-architected status of your FSx for ONTAP file systems]

==== Improvements to actions for configuration issues
From the *Well-architected analysis* tab for an FSx for ONTAP file system, you can select to view only dismissed configurations in the configurations list. You can also select one or more volumes within a file system to fix, dismiss, or reactivate. 

=== Additional notifications for Storage

The NetApp Workload Factory notification service includes notifications for the following:

* Automatic capacity management
* Well-architected issues

link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html#notification-types-and-messages[Notification types and messages in the Workload Factory setup and administration documentation]

=== Immutable files support privileged delete

With this feature, you can configure privileged delete access for immutable files in your FSx for ONTAP file systems. This allows you to protect critical data from accidental or malicious deletion while still enabling authorized users to manage these files as needed. Enabling privileged delete is available during volume creation or for existing volumes.
