=== BlueXP workload factory notification service support
The BlueXP workload factory notification service enables workload factory to send notifications to the BlueXP alerts service or to an Amazon SNS topic. Notifications sent to BlueXP alerts appear in the BlueXP alerts panel. When workload factory publishes notifications to an Amazon SNS topic, subscribers to the topic (such as people or other applications) receive the notifications at the endpoints configured for the topic (such as email or SMS messages).

link:https://docs.netapp.com/us-en/workload-setup-admin/configure-notifications.html[Configure BlueXP workload factory notifications]

=== Storage dashboard adds two new cards regarding savings opportunities 

Two new cards are available in the Storage dashboard. The card at the top of the dashboard displays the number of savings opportunities for any storage environments in Amazon Elastic Block Store (EBS), Amazon FSx for Windows File Server, and Amazon Elastic File Systems (EFS). At the bottom of the dashboard window, you'll find 3 cards that display savings opportunities by Amazon storage service - EBS, FSx for Windows File Server, and EFS.

=== Well-architected analysis update
Workload factory now analyzes your FSx for ONTAP file systems to check whether labels assigned to the snapshot policy of source volume are identical the labels assigned to the long-term retention policy. When labels are identical, data replication is reliable between source and destination volumes.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html[View the well-architected status of data reliability for long-term retention]

=== Support for second-generation Amazon FSx for NetApp ONTAP file systems

Workload factory now supports second-generation Amazon FSx for NetApp ONTAP file systems. You can create, manage, and monitor second-generation file systems in the workload factory console. All new commercial regions are supported. 

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-file-system.html[Create a second-generation file system in workload factory]

=== FlexVol volume support for rebalancing volume capacity


FlexVol volumes are discoverable within the workload factory console. You can check the balance of your FlexVol volumes and rebalance FlexVol volumes to redistribute the capacity when imbalances develop over time due to the addition of new files and file growth.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/rebalance-volume.html[Rebalance the capacity of a FlexVol volume]

=== Enhancements to SMB/CIFS shares creation and management

You can now create SMB/CIFS shares which point to directories within a volume. Within the volume, you'll be able to see which shares exist, where the shares are the pointing to, and the permissions granted to specific users and groups. 

For data protection volumes, the flow of creating an SMB/CIFS share now includes the creation of a junction path to the volume for mounting purposes.

=== Bulk operations for multiple replication relationships

Workload factory now supports bulk operations for multiple replication relationships. You can select multiple replication relationships and perform actions such as initializing, updating, pausing,resuming, reversing, resyncing, breaking, deleting, or  the relationships in bulk. In addition, you can modify long-term retention policies and the max transfer rate for multiple replication relationships at once.

=== Manage IAM execution role and permissions during link creation

Now you can manage the IAM execution role and its attached permission policy when you create a link in the workload factory console. A link establishes connectivity between your workload factory account and one or more FSx for ONTAP file systems. You have two options for assigning the IAM execution role and link permissions - automatically or user-provided. Managing the execution role and its attached permissions policy in workload factory means that you don't need to use third party code any longer.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html[Connect to an FSx for ONTAP file system with a Lambda link]

=== Terminology update 

The term "Autonomous Ransomware Protection" (ARP) has been updated to "NetApp Autonomous Ransomware Protection with AI" (ARP/AI) in the workload factory console. 
