=== Automatic capacity management improvements
Workload factory now scans for available inodes in volumes and increases their count according to the configured automatic capacity management thresholds. You can enable inodes management as part of automatic capacity management. 

link:https://docs.netapp.com/us-en/workload-fsx-ontap/enable-auto-capacity-management.html[Enable automatic capacity management]

=== FlexGroup rebalance API
BlueXP workload factory releases the FlexGroup rebalance API that allows you to execute a plan to rebalance the data in a FlexGroup. Rebalancing redistributes data evenly to the member volumes. 

link:https://console.workloads.netapp.com/api-doc[BlueXP workload factory API documentation]

=== Replication use cases
You can now select one of the following use cases for data replication: migration, hot disaster recovery, cold disaster recovery, or archive. After you select a use case, Workload factory recommends values in the replicate data form in accordance with best practices. 

=== Data tiering policy terminology changes
Now when you select a tiering policy during volume creation or change an existing tiering policy, you'll find new terms to describe the tiering policies. 

* _Balanced (Auto)_
* _Cost-optimized (All)_
* _Performance optimized (Snapshots only)_

You also have the option to copy the source volume tiering policy when migrating your data to FSx for ONTAP. 

