=== Block device clones

Workload Factory offers clones for your block devices so that you can provision writable test/dev copies quickly while controlling capacity, access, and lifecycle.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-block-storage.html[Manage block storage in NetApp Workload Factory]

=== EC2 tags on block devices

The block device table now includes a column that shows tags of the EC2 hosts which are consuming each block device. This helps you identify which host uses each block device during troubleshooting or audits.

To create tags on each block device, deploy an EC2 instance using our provided user script.

link:https://github.com/NetApp/FSx-ONTAP-samples-scripts/tree/main/Management-Utilities/ec2-user-data-iscsi-create-and-mount[EC2 user data script to assign tags to block devices]

=== Well-architected analysis updates

Workload Factory analyzes your FSx for ONTAP file systems for the following configurations:

* Connect host to failover node: checks whether hosts are connected to the failover node in an active-passive FSx for ONTAP file system and recommends connecting hosts to the failover node for reliability.
* Connect host to preferred node: checks whether hosts are connected to the preferred node in a high-availability deployment model and recommends connecting hosts to the preferred node for performance efficiency.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/improve-configurations.html[Implement well-architected FSx for ONTAP file systems]