=== Well-architected analysis updates

Workload Factory analyzes your FSx for ONTAP file systems for the following configurations: 

* Underutilized SSD capacity: checks whether the SSD capacity tier is underutilized and recommends decreasing SSD capacity to optimize costs.
* Inactive NAS volumes: checks whether NAS volumes are inactive and recommends archiving NAS volume data or deleting inactive NAS volumes.
* Schedule volume backups: enhances the configuration recommendation and includes options to enable FSx for ONTAP backup or AWS Backup. FSx for ONTAP backup provides a default policy for all volumes in a file system that includes daily volume backups with a retention period of up to 90 days; AWS Backup provides flexibility like selecting varying retention periods for different volumes in the backup plan for individual volumes.

=== Workload Factory supports AI & ML use case for replication
Workload Factory supports replicating on-premises ONTAP data to FSx for ONTAP and creating S3 access points for AWS Artificial Intelligence (AI) and machine learning (ML) services to accelerate AI/ML workflows.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-replication.html[Replicate on-premises data for AI & ML use cases]

=== Editing existing S3 access points

You can change the user and user type for an existing S3 access point attached to a volume. You can also enable or disable metadata for the access point.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-s3-access-points.html[Edit S3 access points in NetApp Workload Factory]

=== Update to automatic capacity management feature
The update separates the feature into two distinct features: automatic capacity management and capacity notifications. 

Automatic capacity management adds or removes file system capacity to maintain optimal performance. New options include incremental and adaptive modes. Incremental increases capacity by a fixed amount at thresholds; adaptive uses historical data to predict and adjust capacity.

The capacity notifications feature sends alerts when your file systems reach certain capacity limits, so you can manage your storage before issues arise.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/enable-auto-capacity-management.html[Learn about automatic capacity management and capacity notifications in NetApp Workload Factory]

== Cost enhancements

NetApp Workload Factory adds optional page-level filters for file system allocation tag key and value, file system, and volume. Use these filters to analyze costs for specific resources, find ways to save money, and manage your storage costs.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/track-costs.html[Use filters for cost analysis in NetApp Workload Factory]