=== Home page includes well-architected issues for Storage

The NetApp Workload Factory home page includes a Focus tile where well-architected issues appear for your workloads. From there, you can navigate to the Storage Well-Architected screen to view the well-architected status of all FSx for ONTAP file systems in your storage environment and remediate issues.

=== S3 access point enhancements in Storage
Several enhancements have been made to the S3 access point management capabilities in the Storage workload for NetApp Workload Factory. You can input network configuration details for your S3 access points and add S3 access point tags. Additional enhancements include the ability to view S3 bucket details and perform more actions for managing S3 access points.

==== S3 bucket details available in Storage

With metadata enabled for S3 access points, NetApp Workload Factory automatically scans your AWS S3 buckets and populates S3 tables to give you a clear snapshot of all objects, their metadata, attributes, and tags. Access to these details helps you maintain control, visibility, and trust in the data you're responsible for, while reducing operational overhead.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-s3-access-points.html[View details for S3 access points in FSx for ONTAP file systems^]

==== Additional actions provided for managing S3 access points
NetApp Workload Factory now provides additional actions for managing S3 access points in FSx for ONTAP file systems. You can view access point details, modify existing S3 access points, and add or remove S3 access point tags from the NetApp Workload Factory interface, streamlining your object storage management tasks.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-s3-access-points.html[Manage S3 access points in NetApp Workload Factory^]

=== Well-architected analysis updates

Workload Factory analyzes your FSx for ONTAP file systems for the following configurations: 

* Optimize cache volume size: checks whether volume autosize and scrubbing are enabled on cache volumes to maintain optimal size and focus the cache on hot data for peak efficiency.
* Orphaned block devices: recommends archiving block device data or deleting a block device if it hasn't been used for seven consecutive days.
* Storage VM logical reporting: checks whether the default reporting setting for a storage VM is set to logical which provides better visibility into storage usage at the volume level. 

=== Additional cards for block devices
Three new cards have been added to the Block devices tab in the Storage workload to provide quick insights into block device usage and protection status:

* Storage efficiencies: displays used and available storage capacity; used capacity is broken down by SSD and capacity pool storage tiers.
* Protected devices: displays the percentage of block devices with snapshots, remote replication, NetApp Autonomous Ransomware Protection (ARP/AI), and backups.
* Orphan devices: displays if any block devices haven't been used for seven consecutive days, helping you identify and manage unused resources effectively.