=== Support for storage VM disaster recovery 
NetApp Workload Factory now supports disaster recovery for storage VMs. This feature allows migration of ONTAP storage system data and configurations from on-premises ONTAP systems or first-generation FSx for ONTAP file systems to second-generation FSx for ONTAP file systems. You can replicate storage VM data and configuration settings to move to the new file system with minimal downtime and disruption to users and applications. 

To use this feature, link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-replication.html[create a replication relationship] and select "migration" as the use case. To complete the migration process, link:https://docs.netapp.com/us-en/workload-fsx-ontap/cutover-replication.html[cut over replication] to permanently migrate data and storage VM configuration settings from the source file system to the target FSx for ONTAP file system. After cutover, the source volume(s) becomes read-only and the target volume(s) becomes read/write.

