Using configuration analysis insights and recommendations, leverage NetApp to implement best practices for your FSx for ONTAP file systems. You can easily review the well-architected status, learn about issues with your configurations, take action to improve the architecture of any systems that aren't optimized for reliability, security, efficiency, performance, and cost.

You can also dismiss the analysis of specific storage configurations that don't apply to your storage environment to avoid unnecessary alerts and inaccurate optimization results.

link:configuration-analysis.html[Learn about the configuration analysis and well-architected status.]

== About this task
NetApp analyzes Amazon FSx for NetApp ONTAP file system deployment configurations daily. The daily analysis provides the well-architected status, and insights and recommendations with options to automatically fix configuration issues so that your file system meets best practices. 

Link or Console agent connectivity allows NetApp to scan for issues with performance, data protection, and configurations. link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html[Connect to an FSx for ONTAP file system using a link] or link:https://docs.netapp.com/us-en/console-setup-admin/concept-agent-install-options.html[using a Console agent] for the most comprehensive analysis of your file system resources.

You have options to review the recommendations for configuration issues with your file systems and fix the issues. 

Because requirements for storage configurations vary, you can dismiss the analysis of specific configurations that don't apply to your storage environment. This helps you avoid unnecessary alerts and inaccurate optimization results. When a specific configuration analysis is dismissed, the configuration isn't included in the total optimization score.

.What is analyzed
NetApp analyzes the well-architected status of the following configurations for FSx for ONTAP file systems:  

* Reliability: SSD capacity threshold, scheduled local snapshots, schedule volume backups, remote data replication, and data reliability for long-term retention
* Security: NetApp Autonomous Ransomware Protection with AI (ARP/AI) disabled and unauthorized access to volumes
* Operational excellence: automatic capacity management, volume file capacity utilization threshold, volume utilization nearing full, cache relationship write mode, optimize cache volume size, and volume logical capacity reporting
* Cost optimization: storage efficiencies, data tiering, unnecessary snapshot and backup deletion, inactive block devices, underutilized SSD capacity, and inactive NAS volumes