. In Tracker, use the filters or search to narrow job results. You can also download a jobs report.  

== View API request
View the API request in the Codebox for a task in Tracker.

.Steps
. In Tracker, select a task. 
. Select the actions menu and then select *View API request*.

== Retry a failed operation
Retry a failed operation in Tracker. You can also copy the error message of a failed operation. 

NOTE: You can retry a failed operation up to 10 times.

.Steps
. In Tracker, select a failed operation.
. Select the actions menu and then select *Retry*. 

.Result
The operation is re-initiated.

== Edit and retry a failed operation
Edit the parameters of the failed operation and retry the operation outside Tracker. 

.Steps
. In Tracker, select a failed operation.
. Select the actions menu and then select *Edit and retry*.
+
You are redirected to the operation page where you can edit the parameters and retry the operation.

.Result
The operation is re-initiated. Go to Tracker to view the status of the operation.
